=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class BindWebflowFormRequest < ApiModelBase
    attr_accessor :capability

    attr_accessor :connection_id

    attr_accessor :field_mapping

    attr_accessor :form_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'capability' => :'capability',
        :'connection_id' => :'connectionId',
        :'field_mapping' => :'fieldMapping',
        :'form_id' => :'formId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'capability' => :'String',
        :'connection_id' => :'String',
        :'field_mapping' => :'Hash<String, String>',
        :'form_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::BindWebflowFormRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::BindWebflowFormRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'capability')
        self.capability = attributes[:'capability']
      else
        self.capability = nil
      end

      if attributes.key?(:'connection_id')
        self.connection_id = attributes[:'connection_id']
      else
        self.connection_id = nil
      end

      if attributes.key?(:'field_mapping')
        if (value = attributes[:'field_mapping']).is_a?(Hash)
          self.field_mapping = value
        end
      else
        self.field_mapping = nil
      end

      if attributes.key?(:'form_id')
        self.form_id = attributes[:'form_id']
      else
        self.form_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @capability.nil?
        invalid_properties.push('invalid value for "capability", capability cannot be nil.')
      end

      if @connection_id.nil?
        invalid_properties.push('invalid value for "connection_id", connection_id cannot be nil.')
      end

      if @field_mapping.nil?
        invalid_properties.push('invalid value for "field_mapping", field_mapping cannot be nil.')
      end

      if @field_mapping.length > 16
        invalid_properties.push('invalid value for "field_mapping", number of items must be less than or equal to 16.')
      end

      if @field_mapping.length < 1
        invalid_properties.push('invalid value for "field_mapping", number of items must be greater than or equal to 1.')
      end

      if @form_id.nil?
        invalid_properties.push('invalid value for "form_id", form_id cannot be nil.')
      end

      if @form_id.to_s.length > 100
        invalid_properties.push('invalid value for "form_id", the character length must be smaller than or equal to 100.')
      end

      if @form_id.to_s.length < 3
        invalid_properties.push('invalid value for "form_id", the character length must be greater than or equal to 3.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @capability.nil?
      capability_validator = EnumAttributeValidator.new('String', ["email.find", "email.verify", "domain.search"])
      return false unless capability_validator.valid?(@capability)
      return false if @connection_id.nil?
      return false if @field_mapping.nil?
      return false if @field_mapping.length > 16
      return false if @field_mapping.length < 1
      return false if @form_id.nil?
      return false if @form_id.to_s.length > 100
      return false if @form_id.to_s.length < 3
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] capability Object to be assigned
    def capability=(capability)
      validator = EnumAttributeValidator.new('String', ["email.find", "email.verify", "domain.search"])
      unless validator.valid?(capability)
        fail ArgumentError, "invalid value for \"capability\", must be one of #{validator.allowable_values}."
      end
      @capability = capability
    end

    # Custom attribute writer method with validation
    # @param [Object] connection_id Value to be assigned
    def connection_id=(connection_id)
      if connection_id.nil?
        fail ArgumentError, 'connection_id cannot be nil'
      end

      @connection_id = connection_id
    end

    # Custom attribute writer method with validation
    # @param [Object] field_mapping Value to be assigned
    def field_mapping=(field_mapping)
      if field_mapping.nil?
        fail ArgumentError, 'field_mapping cannot be nil'
      end

      if field_mapping.length > 16
        fail ArgumentError, 'invalid value for "field_mapping", number of items must be less than or equal to 16.'
      end

      if field_mapping.length < 1
        fail ArgumentError, 'invalid value for "field_mapping", number of items must be greater than or equal to 1.'
      end

      @field_mapping = field_mapping
    end

    # Custom attribute writer method with validation
    # @param [Object] form_id Value to be assigned
    def form_id=(form_id)
      if form_id.nil?
        fail ArgumentError, 'form_id cannot be nil'
      end

      if form_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "form_id", the character length must be smaller than or equal to 100.'
      end

      if form_id.to_s.length < 3
        fail ArgumentError, 'invalid value for "form_id", the character length must be greater than or equal to 3.'
      end

      @form_id = form_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          capability == o.capability &&
          connection_id == o.connection_id &&
          field_mapping == o.field_mapping &&
          form_id == o.form_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [capability, connection_id, field_mapping, form_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
