=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class ConfigureWarehouseRequest < ApiModelBase
    attr_accessor :config

    attr_accessor :credential

    attr_accessor :label

    attr_accessor :mode

    attr_accessor :provider

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'config' => :'config',
        :'credential' => :'credential',
        :'label' => :'label',
        :'mode' => :'mode',
        :'provider' => :'provider'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'config' => :'Hash<String, String>',
        :'credential' => :'Hash<String, String>',
        :'label' => :'String',
        :'mode' => :'String',
        :'provider' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::ConfigureWarehouseRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::ConfigureWarehouseRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'config')
        if (value = attributes[:'config']).is_a?(Hash)
          self.config = value
        end
      else
        self.config = nil
      end

      if attributes.key?(:'credential')
        if (value = attributes[:'credential']).is_a?(Hash)
          self.credential = value
        end
      else
        self.credential = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      else
        self.provider = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @config.nil?
        invalid_properties.push('invalid value for "config", config cannot be nil.')
      end

      if @config.length > 16
        invalid_properties.push('invalid value for "config", number of items must be less than or equal to 16.')
      end

      if @config.length < 2
        invalid_properties.push('invalid value for "config", number of items must be greater than or equal to 2.')
      end

      if @credential.nil?
        invalid_properties.push('invalid value for "credential", credential cannot be nil.')
      end

      if @credential.length > 8
        invalid_properties.push('invalid value for "credential", number of items must be less than or equal to 8.')
      end

      if @credential.length < 1
        invalid_properties.push('invalid value for "credential", number of items must be greater than or equal to 1.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @label.to_s.length > 120
        invalid_properties.push('invalid value for "label", the character length must be smaller than or equal to 120.')
      end

      if @label.to_s.length < 1
        invalid_properties.push('invalid value for "label", the character length must be greater than or equal to 1.')
      end

      if @provider.nil?
        invalid_properties.push('invalid value for "provider", provider cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @config.nil?
      return false if @config.length > 16
      return false if @config.length < 2
      return false if @credential.nil?
      return false if @credential.length > 8
      return false if @credential.length < 1
      return false if @label.nil?
      return false if @label.to_s.length > 120
      return false if @label.to_s.length < 1
      mode_validator = EnumAttributeValidator.new('String', ["live", "emulated"])
      return false unless mode_validator.valid?(@mode)
      return false if @provider.nil?
      provider_validator = EnumAttributeValidator.new('String', ["postgresql", "bigquery", "snowflake", "redshift"])
      return false unless provider_validator.valid?(@provider)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] config Value to be assigned
    def config=(config)
      if config.nil?
        fail ArgumentError, 'config cannot be nil'
      end

      if config.length > 16
        fail ArgumentError, 'invalid value for "config", number of items must be less than or equal to 16.'
      end

      if config.length < 2
        fail ArgumentError, 'invalid value for "config", number of items must be greater than or equal to 2.'
      end

      @config = config
    end

    # Custom attribute writer method with validation
    # @param [Object] credential Value to be assigned
    def credential=(credential)
      if credential.nil?
        fail ArgumentError, 'credential cannot be nil'
      end

      if credential.length > 8
        fail ArgumentError, 'invalid value for "credential", number of items must be less than or equal to 8.'
      end

      if credential.length < 1
        fail ArgumentError, 'invalid value for "credential", number of items must be greater than or equal to 1.'
      end

      @credential = credential
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      if label.to_s.length > 120
        fail ArgumentError, 'invalid value for "label", the character length must be smaller than or equal to 120.'
      end

      if label.to_s.length < 1
        fail ArgumentError, 'invalid value for "label", the character length must be greater than or equal to 1.'
      end

      @label = label
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mode Object to be assigned
    def mode=(mode)
      validator = EnumAttributeValidator.new('String', ["live", "emulated"])
      unless validator.valid?(mode)
        fail ArgumentError, "invalid value for \"mode\", must be one of #{validator.allowable_values}."
      end
      @mode = mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] provider Object to be assigned
    def provider=(provider)
      validator = EnumAttributeValidator.new('String', ["postgresql", "bigquery", "snowflake", "redshift"])
      unless validator.valid?(provider)
        fail ArgumentError, "invalid value for \"provider\", must be one of #{validator.allowable_values}."
      end
      @provider = provider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          config == o.config &&
          credential == o.credential &&
          label == o.label &&
          mode == o.mode &&
          provider == o.provider
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [config, credential, label, mode, provider].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
