=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class InsightMentionExtractedEvent < ApiModelBase
    attr_accessor :domain

    attr_accessor :email

    attr_accessor :email_moved

    attr_accessor :index

    # Known values: mention_extracted. Clients preserve future values.
    attr_accessor :kind

    attr_accessor :source_type

    attr_accessor :source_url

    attr_accessor :total

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'domain' => :'domain',
        :'email' => :'email',
        :'email_moved' => :'emailMoved',
        :'index' => :'index',
        :'kind' => :'kind',
        :'source_type' => :'sourceType',
        :'source_url' => :'sourceUrl',
        :'total' => :'total'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'domain' => :'String',
        :'email' => :'String',
        :'email_moved' => :'Boolean',
        :'index' => :'Integer',
        :'kind' => :'String',
        :'source_type' => :'String',
        :'source_url' => :'String',
        :'total' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::InsightMentionExtractedEvent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::InsightMentionExtractedEvent`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'email_moved')
        self.email_moved = attributes[:'email_moved']
      else
        self.email_moved = nil
      end

      if attributes.key?(:'index')
        self.index = attributes[:'index']
      else
        self.index = nil
      end

      if attributes.key?(:'kind')
        self.kind = attributes[:'kind']
      else
        self.kind = nil
      end

      if attributes.key?(:'source_type')
        self.source_type = attributes[:'source_type']
      else
        self.source_type = nil
      end

      if attributes.key?(:'source_url')
        self.source_url = attributes[:'source_url']
      else
        self.source_url = nil
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @email_moved.nil?
        invalid_properties.push('invalid value for "email_moved", email_moved cannot be nil.')
      end

      if @index.nil?
        invalid_properties.push('invalid value for "index", index cannot be nil.')
      end

      if @kind.nil?
        invalid_properties.push('invalid value for "kind", kind cannot be nil.')
      end

      if @source_type.nil?
        invalid_properties.push('invalid value for "source_type", source_type cannot be nil.')
      end

      if @source_url.nil?
        invalid_properties.push('invalid value for "source_url", source_url cannot be nil.')
      end

      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @domain.nil?
      return false if @email.nil?
      return false if @email_moved.nil?
      return false if @index.nil?
      return false if @kind.nil?
      return false if @source_type.nil?
      return false if @source_url.nil?
      return false if @total.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] email_moved Value to be assigned
    def email_moved=(email_moved)
      if email_moved.nil?
        fail ArgumentError, 'email_moved cannot be nil'
      end

      @email_moved = email_moved
    end

    # Custom attribute writer method with validation
    # @param [Object] index Value to be assigned
    def index=(index)
      if index.nil?
        fail ArgumentError, 'index cannot be nil'
      end

      @index = index
    end

    # Custom attribute writer method with validation
    # @param [Object] kind Value to be assigned
    def kind=(kind)
      if kind.nil?
        fail ArgumentError, 'kind cannot be nil'
      end

      @kind = kind
    end

    # Custom attribute writer method with validation
    # @param [Object] source_type Value to be assigned
    def source_type=(source_type)
      if source_type.nil?
        fail ArgumentError, 'source_type cannot be nil'
      end

      @source_type = source_type
    end

    # Custom attribute writer method with validation
    # @param [Object] source_url Value to be assigned
    def source_url=(source_url)
      if source_url.nil?
        fail ArgumentError, 'source_url cannot be nil'
      end

      @source_url = source_url
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        fail ArgumentError, 'total cannot be nil'
      end

      @total = total
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          domain == o.domain &&
          email == o.email &&
          email_moved == o.email_moved &&
          index == o.index &&
          kind == o.kind &&
          source_type == o.source_type &&
          source_url == o.source_url &&
          total == o.total
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [domain, email, email_moved, index, kind, source_type, source_url, total].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
