=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class InspectGoogleSheetRequest < ApiModelBase
    attr_accessor :connection_id

    attr_accessor :header_row

    attr_accessor :sheet_name

    attr_accessor :spreadsheet_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'connection_id' => :'connectionId',
        :'header_row' => :'headerRow',
        :'sheet_name' => :'sheetName',
        :'spreadsheet_id' => :'spreadsheetId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'connection_id' => :'String',
        :'header_row' => :'Integer',
        :'sheet_name' => :'String',
        :'spreadsheet_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'sheet_name',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::InspectGoogleSheetRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::InspectGoogleSheetRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'connection_id')
        self.connection_id = attributes[:'connection_id']
      else
        self.connection_id = nil
      end

      if attributes.key?(:'header_row')
        self.header_row = attributes[:'header_row']
      end

      if attributes.key?(:'sheet_name')
        self.sheet_name = attributes[:'sheet_name']
      end

      if attributes.key?(:'spreadsheet_id')
        self.spreadsheet_id = attributes[:'spreadsheet_id']
      else
        self.spreadsheet_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @connection_id.nil?
        invalid_properties.push('invalid value for "connection_id", connection_id cannot be nil.')
      end

      if @connection_id.to_s.length > 100
        invalid_properties.push('invalid value for "connection_id", the character length must be smaller than or equal to 100.')
      end

      if @connection_id.to_s.length < 1
        invalid_properties.push('invalid value for "connection_id", the character length must be greater than or equal to 1.')
      end

      if !@header_row.nil? && @header_row > 1000
        invalid_properties.push('invalid value for "header_row", must be smaller than or equal to 1000.')
      end

      if !@header_row.nil? && @header_row < 1
        invalid_properties.push('invalid value for "header_row", must be greater than or equal to 1.')
      end

      if !@sheet_name.nil? && @sheet_name.to_s.length > 500
        invalid_properties.push('invalid value for "sheet_name", the character length must be smaller than or equal to 500.')
      end

      if @spreadsheet_id.nil?
        invalid_properties.push('invalid value for "spreadsheet_id", spreadsheet_id cannot be nil.')
      end

      if @spreadsheet_id.to_s.length > 100
        invalid_properties.push('invalid value for "spreadsheet_id", the character length must be smaller than or equal to 100.')
      end

      if @spreadsheet_id.to_s.length < 20
        invalid_properties.push('invalid value for "spreadsheet_id", the character length must be greater than or equal to 20.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @connection_id.nil?
      return false if @connection_id.to_s.length > 100
      return false if @connection_id.to_s.length < 1
      return false if !@header_row.nil? && @header_row > 1000
      return false if !@header_row.nil? && @header_row < 1
      return false if !@sheet_name.nil? && @sheet_name.to_s.length > 500
      return false if @spreadsheet_id.nil?
      return false if @spreadsheet_id.to_s.length > 100
      return false if @spreadsheet_id.to_s.length < 20
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] connection_id Value to be assigned
    def connection_id=(connection_id)
      if connection_id.nil?
        fail ArgumentError, 'connection_id cannot be nil'
      end

      if connection_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "connection_id", the character length must be smaller than or equal to 100.'
      end

      if connection_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "connection_id", the character length must be greater than or equal to 1.'
      end

      @connection_id = connection_id
    end

    # Custom attribute writer method with validation
    # @param [Object] header_row Value to be assigned
    def header_row=(header_row)
      if header_row.nil?
        fail ArgumentError, 'header_row cannot be nil'
      end

      if header_row > 1000
        fail ArgumentError, 'invalid value for "header_row", must be smaller than or equal to 1000.'
      end

      if header_row < 1
        fail ArgumentError, 'invalid value for "header_row", must be greater than or equal to 1.'
      end

      @header_row = header_row
    end

    # Custom attribute writer method with validation
    # @param [Object] sheet_name Value to be assigned
    def sheet_name=(sheet_name)
      if !sheet_name.nil? && sheet_name.to_s.length > 500
        fail ArgumentError, 'invalid value for "sheet_name", the character length must be smaller than or equal to 500.'
      end

      @sheet_name = sheet_name
    end

    # Custom attribute writer method with validation
    # @param [Object] spreadsheet_id Value to be assigned
    def spreadsheet_id=(spreadsheet_id)
      if spreadsheet_id.nil?
        fail ArgumentError, 'spreadsheet_id cannot be nil'
      end

      if spreadsheet_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "spreadsheet_id", the character length must be smaller than or equal to 100.'
      end

      if spreadsheet_id.to_s.length < 20
        fail ArgumentError, 'invalid value for "spreadsheet_id", the character length must be greater than or equal to 20.'
      end

      @spreadsheet_id = spreadsheet_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          connection_id == o.connection_id &&
          header_row == o.header_row &&
          sheet_name == o.sheet_name &&
          spreadsheet_id == o.spreadsheet_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [connection_id, header_row, sheet_name, spreadsheet_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
