=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class IntegrationJobCounters < ApiModelBase
    attr_accessor :failed

    attr_accessor :processed

    attr_accessor :skipped

    attr_accessor :succeeded

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'failed' => :'failed',
        :'processed' => :'processed',
        :'skipped' => :'skipped',
        :'succeeded' => :'succeeded'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'failed' => :'Integer',
        :'processed' => :'Integer',
        :'skipped' => :'Integer',
        :'succeeded' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::IntegrationJobCounters` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::IntegrationJobCounters`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'failed')
        self.failed = attributes[:'failed']
      else
        self.failed = nil
      end

      if attributes.key?(:'processed')
        self.processed = attributes[:'processed']
      else
        self.processed = nil
      end

      if attributes.key?(:'skipped')
        self.skipped = attributes[:'skipped']
      else
        self.skipped = nil
      end

      if attributes.key?(:'succeeded')
        self.succeeded = attributes[:'succeeded']
      else
        self.succeeded = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @failed.nil?
        invalid_properties.push('invalid value for "failed", failed cannot be nil.')
      end

      if @failed < 0
        invalid_properties.push('invalid value for "failed", must be greater than or equal to 0.')
      end

      if @processed.nil?
        invalid_properties.push('invalid value for "processed", processed cannot be nil.')
      end

      if @processed < 0
        invalid_properties.push('invalid value for "processed", must be greater than or equal to 0.')
      end

      if @skipped.nil?
        invalid_properties.push('invalid value for "skipped", skipped cannot be nil.')
      end

      if @skipped < 0
        invalid_properties.push('invalid value for "skipped", must be greater than or equal to 0.')
      end

      if @succeeded.nil?
        invalid_properties.push('invalid value for "succeeded", succeeded cannot be nil.')
      end

      if @succeeded < 0
        invalid_properties.push('invalid value for "succeeded", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @failed.nil?
      return false if @failed < 0
      return false if @processed.nil?
      return false if @processed < 0
      return false if @skipped.nil?
      return false if @skipped < 0
      return false if @succeeded.nil?
      return false if @succeeded < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] failed Value to be assigned
    def failed=(failed)
      if failed.nil?
        fail ArgumentError, 'failed cannot be nil'
      end

      if failed < 0
        fail ArgumentError, 'invalid value for "failed", must be greater than or equal to 0.'
      end

      @failed = failed
    end

    # Custom attribute writer method with validation
    # @param [Object] processed Value to be assigned
    def processed=(processed)
      if processed.nil?
        fail ArgumentError, 'processed cannot be nil'
      end

      if processed < 0
        fail ArgumentError, 'invalid value for "processed", must be greater than or equal to 0.'
      end

      @processed = processed
    end

    # Custom attribute writer method with validation
    # @param [Object] skipped Value to be assigned
    def skipped=(skipped)
      if skipped.nil?
        fail ArgumentError, 'skipped cannot be nil'
      end

      if skipped < 0
        fail ArgumentError, 'invalid value for "skipped", must be greater than or equal to 0.'
      end

      @skipped = skipped
    end

    # Custom attribute writer method with validation
    # @param [Object] succeeded Value to be assigned
    def succeeded=(succeeded)
      if succeeded.nil?
        fail ArgumentError, 'succeeded cannot be nil'
      end

      if succeeded < 0
        fail ArgumentError, 'invalid value for "succeeded", must be greater than or equal to 0.'
      end

      @succeeded = succeeded
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          failed == o.failed &&
          processed == o.processed &&
          skipped == o.skipped &&
          succeeded == o.succeeded
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [failed, processed, skipped, succeeded].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
