=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailMessagePolicy < ApiModelBase
    attr_accessor :domain_quotas

    attr_accessor :mailbox_quotas

    attr_accessor :recipient_cooldown_ms

    attr_accessor :recipient_quotas

    attr_accessor :sending_windows

    attr_accessor :tenant_quotas

    attr_accessor :time_zone

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'domain_quotas' => :'domainQuotas',
        :'mailbox_quotas' => :'mailboxQuotas',
        :'recipient_cooldown_ms' => :'recipientCooldownMs',
        :'recipient_quotas' => :'recipientQuotas',
        :'sending_windows' => :'sendingWindows',
        :'tenant_quotas' => :'tenantQuotas',
        :'time_zone' => :'timeZone'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'domain_quotas' => :'Array<MailQuotaRule>',
        :'mailbox_quotas' => :'Array<MailQuotaRule>',
        :'recipient_cooldown_ms' => :'Float',
        :'recipient_quotas' => :'Array<MailQuotaRule>',
        :'sending_windows' => :'Array<MailSendingWindow>',
        :'tenant_quotas' => :'Array<MailQuotaRule>',
        :'time_zone' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailMessagePolicy` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailMessagePolicy`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'domain_quotas')
        if (value = attributes[:'domain_quotas']).is_a?(Array)
          self.domain_quotas = value
        end
      else
        self.domain_quotas = nil
      end

      if attributes.key?(:'mailbox_quotas')
        if (value = attributes[:'mailbox_quotas']).is_a?(Array)
          self.mailbox_quotas = value
        end
      else
        self.mailbox_quotas = nil
      end

      if attributes.key?(:'recipient_cooldown_ms')
        self.recipient_cooldown_ms = attributes[:'recipient_cooldown_ms']
      end

      if attributes.key?(:'recipient_quotas')
        if (value = attributes[:'recipient_quotas']).is_a?(Array)
          self.recipient_quotas = value
        end
      else
        self.recipient_quotas = nil
      end

      if attributes.key?(:'sending_windows')
        if (value = attributes[:'sending_windows']).is_a?(Array)
          self.sending_windows = value
        end
      else
        self.sending_windows = nil
      end

      if attributes.key?(:'tenant_quotas')
        if (value = attributes[:'tenant_quotas']).is_a?(Array)
          self.tenant_quotas = value
        end
      else
        self.tenant_quotas = nil
      end

      if attributes.key?(:'time_zone')
        self.time_zone = attributes[:'time_zone']
      else
        self.time_zone = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @domain_quotas.nil?
        invalid_properties.push('invalid value for "domain_quotas", domain_quotas cannot be nil.')
      end

      if @mailbox_quotas.nil?
        invalid_properties.push('invalid value for "mailbox_quotas", mailbox_quotas cannot be nil.')
      end

      if @recipient_quotas.nil?
        invalid_properties.push('invalid value for "recipient_quotas", recipient_quotas cannot be nil.')
      end

      if @sending_windows.nil?
        invalid_properties.push('invalid value for "sending_windows", sending_windows cannot be nil.')
      end

      if @tenant_quotas.nil?
        invalid_properties.push('invalid value for "tenant_quotas", tenant_quotas cannot be nil.')
      end

      if @time_zone.nil?
        invalid_properties.push('invalid value for "time_zone", time_zone cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @domain_quotas.nil?
      return false if @mailbox_quotas.nil?
      return false if @recipient_quotas.nil?
      return false if @sending_windows.nil?
      return false if @tenant_quotas.nil?
      return false if @time_zone.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] domain_quotas Value to be assigned
    def domain_quotas=(domain_quotas)
      if domain_quotas.nil?
        fail ArgumentError, 'domain_quotas cannot be nil'
      end

      @domain_quotas = domain_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_quotas Value to be assigned
    def mailbox_quotas=(mailbox_quotas)
      if mailbox_quotas.nil?
        fail ArgumentError, 'mailbox_quotas cannot be nil'
      end

      @mailbox_quotas = mailbox_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] recipient_quotas Value to be assigned
    def recipient_quotas=(recipient_quotas)
      if recipient_quotas.nil?
        fail ArgumentError, 'recipient_quotas cannot be nil'
      end

      @recipient_quotas = recipient_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] sending_windows Value to be assigned
    def sending_windows=(sending_windows)
      if sending_windows.nil?
        fail ArgumentError, 'sending_windows cannot be nil'
      end

      @sending_windows = sending_windows
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_quotas Value to be assigned
    def tenant_quotas=(tenant_quotas)
      if tenant_quotas.nil?
        fail ArgumentError, 'tenant_quotas cannot be nil'
      end

      @tenant_quotas = tenant_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] time_zone Value to be assigned
    def time_zone=(time_zone)
      if time_zone.nil?
        fail ArgumentError, 'time_zone cannot be nil'
      end

      @time_zone = time_zone
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          domain_quotas == o.domain_quotas &&
          mailbox_quotas == o.mailbox_quotas &&
          recipient_cooldown_ms == o.recipient_cooldown_ms &&
          recipient_quotas == o.recipient_quotas &&
          sending_windows == o.sending_windows &&
          tenant_quotas == o.tenant_quotas &&
          time_zone == o.time_zone
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [domain_quotas, mailbox_quotas, recipient_cooldown_ms, recipient_quotas, sending_windows, tenant_quotas, time_zone].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
