=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailMessageAnalyticsOverviewVariantsInner < ApiModelBase
    attr_accessor :accepted

    attr_accessor :bounced

    attr_accessor :campaign_id

    attr_accessor :complained

    attr_accessor :experiment_id

    attr_accessor :experiment_name

    attr_accessor :replied

    attr_accessor :step_id

    attr_accessor :total

    attr_accessor :variant_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'accepted' => :'accepted',
        :'bounced' => :'bounced',
        :'campaign_id' => :'campaignId',
        :'complained' => :'complained',
        :'experiment_id' => :'experimentId',
        :'experiment_name' => :'experimentName',
        :'replied' => :'replied',
        :'step_id' => :'stepId',
        :'total' => :'total',
        :'variant_id' => :'variantId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'accepted' => :'Float',
        :'bounced' => :'Float',
        :'campaign_id' => :'String',
        :'complained' => :'Float',
        :'experiment_id' => :'String',
        :'experiment_name' => :'String',
        :'replied' => :'Float',
        :'step_id' => :'String',
        :'total' => :'Float',
        :'variant_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailMessageAnalyticsOverviewVariantsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailMessageAnalyticsOverviewVariantsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'accepted')
        self.accepted = attributes[:'accepted']
      else
        self.accepted = nil
      end

      if attributes.key?(:'bounced')
        self.bounced = attributes[:'bounced']
      else
        self.bounced = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.key?(:'complained')
        self.complained = attributes[:'complained']
      else
        self.complained = nil
      end

      if attributes.key?(:'experiment_id')
        self.experiment_id = attributes[:'experiment_id']
      end

      if attributes.key?(:'experiment_name')
        self.experiment_name = attributes[:'experiment_name']
      end

      if attributes.key?(:'replied')
        self.replied = attributes[:'replied']
      else
        self.replied = nil
      end

      if attributes.key?(:'step_id')
        self.step_id = attributes[:'step_id']
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end

      if attributes.key?(:'variant_id')
        self.variant_id = attributes[:'variant_id']
      else
        self.variant_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @accepted.nil?
        invalid_properties.push('invalid value for "accepted", accepted cannot be nil.')
      end

      if @bounced.nil?
        invalid_properties.push('invalid value for "bounced", bounced cannot be nil.')
      end

      if @complained.nil?
        invalid_properties.push('invalid value for "complained", complained cannot be nil.')
      end

      if @replied.nil?
        invalid_properties.push('invalid value for "replied", replied cannot be nil.')
      end

      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      if @variant_id.nil?
        invalid_properties.push('invalid value for "variant_id", variant_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @accepted.nil?
      return false if @bounced.nil?
      return false if @complained.nil?
      return false if @replied.nil?
      return false if @total.nil?
      return false if @variant_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] accepted Value to be assigned
    def accepted=(accepted)
      if accepted.nil?
        fail ArgumentError, 'accepted cannot be nil'
      end

      @accepted = accepted
    end

    # Custom attribute writer method with validation
    # @param [Object] bounced Value to be assigned
    def bounced=(bounced)
      if bounced.nil?
        fail ArgumentError, 'bounced cannot be nil'
      end

      @bounced = bounced
    end

    # Custom attribute writer method with validation
    # @param [Object] complained Value to be assigned
    def complained=(complained)
      if complained.nil?
        fail ArgumentError, 'complained cannot be nil'
      end

      @complained = complained
    end

    # Custom attribute writer method with validation
    # @param [Object] replied Value to be assigned
    def replied=(replied)
      if replied.nil?
        fail ArgumentError, 'replied cannot be nil'
      end

      @replied = replied
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        fail ArgumentError, 'total cannot be nil'
      end

      @total = total
    end

    # Custom attribute writer method with validation
    # @param [Object] variant_id Value to be assigned
    def variant_id=(variant_id)
      if variant_id.nil?
        fail ArgumentError, 'variant_id cannot be nil'
      end

      @variant_id = variant_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          accepted == o.accepted &&
          bounced == o.bounced &&
          campaign_id == o.campaign_id &&
          complained == o.complained &&
          experiment_id == o.experiment_id &&
          experiment_name == o.experiment_name &&
          replied == o.replied &&
          step_id == o.step_id &&
          total == o.total &&
          variant_id == o.variant_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [accepted, bounced, campaign_id, complained, experiment_id, experiment_name, replied, step_id, total, variant_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
