=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPostCampaignsByCampaignIdLaunchResponse200AnyOf < ApiModelBase
    attr_accessor :campaign

    attr_accessor :draft

    attr_accessor :sequences

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'campaign' => :'campaign',
        :'draft' => :'draft',
        :'sequences' => :'sequences'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'campaign' => :'MailPostCampaignsByCampaignIdLaunchResponse200Campaign',
        :'draft' => :'MailCampaignDraftRecord',
        :'sequences' => :'Array<Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPostCampaignsByCampaignIdLaunchResponse200AnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPostCampaignsByCampaignIdLaunchResponse200AnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'campaign')
        self.campaign = attributes[:'campaign']
      else
        self.campaign = nil
      end

      if attributes.key?(:'draft')
        self.draft = attributes[:'draft']
      else
        self.draft = nil
      end

      if attributes.key?(:'sequences')
        if (value = attributes[:'sequences']).is_a?(Array)
          self.sequences = value
        end
      else
        self.sequences = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @campaign.nil?
        invalid_properties.push('invalid value for "campaign", campaign cannot be nil.')
      end

      if @draft.nil?
        invalid_properties.push('invalid value for "draft", draft cannot be nil.')
      end

      if @sequences.nil?
        invalid_properties.push('invalid value for "sequences", sequences cannot be nil.')
      end

      if @sequences.length > 0
        invalid_properties.push('invalid value for "sequences", number of items must be less than or equal to 0.')
      end

      if @sequences.length < 0
        invalid_properties.push('invalid value for "sequences", number of items must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @campaign.nil?
      return false if @draft.nil?
      return false if @sequences.nil?
      return false if @sequences.length > 0
      return false if @sequences.length < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign Value to be assigned
    def campaign=(campaign)
      if campaign.nil?
        fail ArgumentError, 'campaign cannot be nil'
      end

      @campaign = campaign
    end

    # Custom attribute writer method with validation
    # @param [Object] draft Value to be assigned
    def draft=(draft)
      if draft.nil?
        fail ArgumentError, 'draft cannot be nil'
      end

      @draft = draft
    end

    # Custom attribute writer method with validation
    # @param [Object] sequences Value to be assigned
    def sequences=(sequences)
      if sequences.nil?
        fail ArgumentError, 'sequences cannot be nil'
      end

      if sequences.length > 0
        fail ArgumentError, 'invalid value for "sequences", number of items must be less than or equal to 0.'
      end

      if sequences.length < 0
        fail ArgumentError, 'invalid value for "sequences", number of items must be greater than or equal to 0.'
      end

      @sequences = sequences
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          campaign == o.campaign &&
          draft == o.draft &&
          sequences == o.sequences
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [campaign, draft, sequences].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
