=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPostMailboxesManualRequest < ApiModelBase
    attr_accessor :daily_limit

    attr_accessor :email

    attr_accessor :hourly_limit

    attr_accessor :imap

    attr_accessor :name

    attr_accessor :ramp_enabled

    attr_accessor :ramp_interval_hours

    attr_accessor :ramp_step

    attr_accessor :smtp

    attr_accessor :starting_daily_limit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'daily_limit' => :'dailyLimit',
        :'email' => :'email',
        :'hourly_limit' => :'hourlyLimit',
        :'imap' => :'imap',
        :'name' => :'name',
        :'ramp_enabled' => :'rampEnabled',
        :'ramp_interval_hours' => :'rampIntervalHours',
        :'ramp_step' => :'rampStep',
        :'smtp' => :'smtp',
        :'starting_daily_limit' => :'startingDailyLimit'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'daily_limit' => :'Integer',
        :'email' => :'String',
        :'hourly_limit' => :'Integer',
        :'imap' => :'MailPostMailboxesManualRequestImap',
        :'name' => :'String',
        :'ramp_enabled' => :'Boolean',
        :'ramp_interval_hours' => :'Integer',
        :'ramp_step' => :'Integer',
        :'smtp' => :'MailPostMailboxesManualRequestSmtp',
        :'starting_daily_limit' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPostMailboxesManualRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPostMailboxesManualRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'daily_limit')
        self.daily_limit = attributes[:'daily_limit']
      else
        self.daily_limit = 500
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'hourly_limit')
        self.hourly_limit = attributes[:'hourly_limit']
      else
        self.hourly_limit = 100
      end

      if attributes.key?(:'imap')
        self.imap = attributes[:'imap']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'ramp_enabled')
        self.ramp_enabled = attributes[:'ramp_enabled']
      else
        self.ramp_enabled = false
      end

      if attributes.key?(:'ramp_interval_hours')
        self.ramp_interval_hours = attributes[:'ramp_interval_hours']
      else
        self.ramp_interval_hours = 24
      end

      if attributes.key?(:'ramp_step')
        self.ramp_step = attributes[:'ramp_step']
      else
        self.ramp_step = 3
      end

      if attributes.key?(:'smtp')
        self.smtp = attributes[:'smtp']
      else
        self.smtp = nil
      end

      if attributes.key?(:'starting_daily_limit')
        self.starting_daily_limit = attributes[:'starting_daily_limit']
      else
        self.starting_daily_limit = 3
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@daily_limit.nil? && @daily_limit > 100000
        invalid_properties.push('invalid value for "daily_limit", must be smaller than or equal to 100000.')
      end

      if !@daily_limit.nil? && @daily_limit <= 0
        invalid_properties.push('invalid value for "daily_limit", must be greater than 0.')
      end

      if @email.nil?
        invalid_properties.push('invalid value for "email", email cannot be nil.')
      end

      if @email.to_s.length > 320
        invalid_properties.push('invalid value for "email", the character length must be smaller than or equal to 320.')
      end

      if !@hourly_limit.nil? && @hourly_limit > 10000
        invalid_properties.push('invalid value for "hourly_limit", must be smaller than or equal to 10000.')
      end

      if !@hourly_limit.nil? && @hourly_limit <= 0
        invalid_properties.push('invalid value for "hourly_limit", must be greater than 0.')
      end

      if !@name.nil? && @name.to_s.length > 100
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 100.')
      end

      if !@name.nil? && @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@ramp_interval_hours.nil? && @ramp_interval_hours > 720
        invalid_properties.push('invalid value for "ramp_interval_hours", must be smaller than or equal to 720.')
      end

      if !@ramp_interval_hours.nil? && @ramp_interval_hours <= 0
        invalid_properties.push('invalid value for "ramp_interval_hours", must be greater than 0.')
      end

      if !@ramp_step.nil? && @ramp_step > 100000
        invalid_properties.push('invalid value for "ramp_step", must be smaller than or equal to 100000.')
      end

      if !@ramp_step.nil? && @ramp_step <= 0
        invalid_properties.push('invalid value for "ramp_step", must be greater than 0.')
      end

      if @smtp.nil?
        invalid_properties.push('invalid value for "smtp", smtp cannot be nil.')
      end

      if !@starting_daily_limit.nil? && @starting_daily_limit > 100000
        invalid_properties.push('invalid value for "starting_daily_limit", must be smaller than or equal to 100000.')
      end

      if !@starting_daily_limit.nil? && @starting_daily_limit <= 0
        invalid_properties.push('invalid value for "starting_daily_limit", must be greater than 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@daily_limit.nil? && @daily_limit > 100000
      return false if !@daily_limit.nil? && @daily_limit <= 0
      return false if @email.nil?
      return false if @email.to_s.length > 320
      return false if !@hourly_limit.nil? && @hourly_limit > 10000
      return false if !@hourly_limit.nil? && @hourly_limit <= 0
      return false if !@name.nil? && @name.to_s.length > 100
      return false if !@name.nil? && @name.to_s.length < 1
      return false if !@ramp_interval_hours.nil? && @ramp_interval_hours > 720
      return false if !@ramp_interval_hours.nil? && @ramp_interval_hours <= 0
      return false if !@ramp_step.nil? && @ramp_step > 100000
      return false if !@ramp_step.nil? && @ramp_step <= 0
      return false if @smtp.nil?
      return false if !@starting_daily_limit.nil? && @starting_daily_limit > 100000
      return false if !@starting_daily_limit.nil? && @starting_daily_limit <= 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] daily_limit Value to be assigned
    def daily_limit=(daily_limit)
      if daily_limit.nil?
        fail ArgumentError, 'daily_limit cannot be nil'
      end

      if daily_limit > 100000
        fail ArgumentError, 'invalid value for "daily_limit", must be smaller than or equal to 100000.'
      end

      if daily_limit <= 0
        fail ArgumentError, 'invalid value for "daily_limit", must be greater than 0.'
      end

      @daily_limit = daily_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      if email.nil?
        fail ArgumentError, 'email cannot be nil'
      end

      if email.to_s.length > 320
        fail ArgumentError, 'invalid value for "email", the character length must be smaller than or equal to 320.'
      end

      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] hourly_limit Value to be assigned
    def hourly_limit=(hourly_limit)
      if hourly_limit.nil?
        fail ArgumentError, 'hourly_limit cannot be nil'
      end

      if hourly_limit > 10000
        fail ArgumentError, 'invalid value for "hourly_limit", must be smaller than or equal to 10000.'
      end

      if hourly_limit <= 0
        fail ArgumentError, 'invalid value for "hourly_limit", must be greater than 0.'
      end

      @hourly_limit = hourly_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 100
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 100.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] ramp_interval_hours Value to be assigned
    def ramp_interval_hours=(ramp_interval_hours)
      if ramp_interval_hours.nil?
        fail ArgumentError, 'ramp_interval_hours cannot be nil'
      end

      if ramp_interval_hours > 720
        fail ArgumentError, 'invalid value for "ramp_interval_hours", must be smaller than or equal to 720.'
      end

      if ramp_interval_hours <= 0
        fail ArgumentError, 'invalid value for "ramp_interval_hours", must be greater than 0.'
      end

      @ramp_interval_hours = ramp_interval_hours
    end

    # Custom attribute writer method with validation
    # @param [Object] ramp_step Value to be assigned
    def ramp_step=(ramp_step)
      if ramp_step.nil?
        fail ArgumentError, 'ramp_step cannot be nil'
      end

      if ramp_step > 100000
        fail ArgumentError, 'invalid value for "ramp_step", must be smaller than or equal to 100000.'
      end

      if ramp_step <= 0
        fail ArgumentError, 'invalid value for "ramp_step", must be greater than 0.'
      end

      @ramp_step = ramp_step
    end

    # Custom attribute writer method with validation
    # @param [Object] smtp Value to be assigned
    def smtp=(smtp)
      if smtp.nil?
        fail ArgumentError, 'smtp cannot be nil'
      end

      @smtp = smtp
    end

    # Custom attribute writer method with validation
    # @param [Object] starting_daily_limit Value to be assigned
    def starting_daily_limit=(starting_daily_limit)
      if starting_daily_limit.nil?
        fail ArgumentError, 'starting_daily_limit cannot be nil'
      end

      if starting_daily_limit > 100000
        fail ArgumentError, 'invalid value for "starting_daily_limit", must be smaller than or equal to 100000.'
      end

      if starting_daily_limit <= 0
        fail ArgumentError, 'invalid value for "starting_daily_limit", must be greater than 0.'
      end

      @starting_daily_limit = starting_daily_limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          daily_limit == o.daily_limit &&
          email == o.email &&
          hourly_limit == o.hourly_limit &&
          imap == o.imap &&
          name == o.name &&
          ramp_enabled == o.ramp_enabled &&
          ramp_interval_hours == o.ramp_interval_hours &&
          ramp_step == o.ramp_step &&
          smtp == o.smtp &&
          starting_daily_limit == o.starting_daily_limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [daily_limit, email, hourly_limit, imap, name, ramp_enabled, ramp_interval_hours, ramp_step, smtp, starting_daily_limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
