=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPatchCampaignsByCampaignIdRequest < ApiModelBase
    attr_accessor :audience_list_ids

    attr_accessor :expected_version

    attr_accessor :mailbox_ids

    attr_accessor :mailbox_pool_id

    attr_accessor :name

    attr_accessor :policy

    attr_accessor :scheduled_at

    attr_accessor :steps

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'audience_list_ids' => :'audienceListIds',
        :'expected_version' => :'expectedVersion',
        :'mailbox_ids' => :'mailboxIds',
        :'mailbox_pool_id' => :'mailboxPoolId',
        :'name' => :'name',
        :'policy' => :'policy',
        :'scheduled_at' => :'scheduledAt',
        :'steps' => :'steps'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'audience_list_ids' => :'Array<String>',
        :'expected_version' => :'Integer',
        :'mailbox_ids' => :'Array<String>',
        :'mailbox_pool_id' => :'String',
        :'name' => :'String',
        :'policy' => :'MailPatchCampaignsByCampaignIdRequestPolicy',
        :'scheduled_at' => :'Time',
        :'steps' => :'Array<MailPatchCampaignsByCampaignIdRequestStepsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPatchCampaignsByCampaignIdRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPatchCampaignsByCampaignIdRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'audience_list_ids')
        if (value = attributes[:'audience_list_ids']).is_a?(Array)
          self.audience_list_ids = value
        end
      end

      if attributes.key?(:'expected_version')
        self.expected_version = attributes[:'expected_version']
      else
        self.expected_version = nil
      end

      if attributes.key?(:'mailbox_ids')
        if (value = attributes[:'mailbox_ids']).is_a?(Array)
          self.mailbox_ids = value
        end
      end

      if attributes.key?(:'mailbox_pool_id')
        self.mailbox_pool_id = attributes[:'mailbox_pool_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'policy')
        self.policy = attributes[:'policy']
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      end

      if attributes.key?(:'steps')
        if (value = attributes[:'steps']).is_a?(Array)
          self.steps = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@audience_list_ids.nil? && @audience_list_ids.length > 100
        invalid_properties.push('invalid value for "audience_list_ids", number of items must be less than or equal to 100.')
      end

      if @expected_version.nil?
        invalid_properties.push('invalid value for "expected_version", expected_version cannot be nil.')
      end

      if @expected_version <= 0
        invalid_properties.push('invalid value for "expected_version", must be greater than 0.')
      end

      if !@mailbox_ids.nil? && @mailbox_ids.length > 100
        invalid_properties.push('invalid value for "mailbox_ids", number of items must be less than or equal to 100.')
      end

      if !@mailbox_pool_id.nil? && @mailbox_pool_id.to_s.length > 200
        invalid_properties.push('invalid value for "mailbox_pool_id", the character length must be smaller than or equal to 200.')
      end

      if !@mailbox_pool_id.nil? && @mailbox_pool_id.to_s.length < 1
        invalid_properties.push('invalid value for "mailbox_pool_id", the character length must be greater than or equal to 1.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 200
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 200.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@steps.nil? && @steps.length > 50
        invalid_properties.push('invalid value for "steps", number of items must be less than or equal to 50.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@audience_list_ids.nil? && @audience_list_ids.length > 100
      return false if @expected_version.nil?
      return false if @expected_version <= 0
      return false if !@mailbox_ids.nil? && @mailbox_ids.length > 100
      return false if !@mailbox_pool_id.nil? && @mailbox_pool_id.to_s.length > 200
      return false if !@mailbox_pool_id.nil? && @mailbox_pool_id.to_s.length < 1
      return false if @name.nil?
      return false if @name.to_s.length > 200
      return false if @name.to_s.length < 1
      return false if !@steps.nil? && @steps.length > 50
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] audience_list_ids Value to be assigned
    def audience_list_ids=(audience_list_ids)
      if audience_list_ids.nil?
        fail ArgumentError, 'audience_list_ids cannot be nil'
      end

      if audience_list_ids.length > 100
        fail ArgumentError, 'invalid value for "audience_list_ids", number of items must be less than or equal to 100.'
      end

      @audience_list_ids = audience_list_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] expected_version Value to be assigned
    def expected_version=(expected_version)
      if expected_version.nil?
        fail ArgumentError, 'expected_version cannot be nil'
      end

      if expected_version <= 0
        fail ArgumentError, 'invalid value for "expected_version", must be greater than 0.'
      end

      @expected_version = expected_version
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_ids Value to be assigned
    def mailbox_ids=(mailbox_ids)
      if mailbox_ids.nil?
        fail ArgumentError, 'mailbox_ids cannot be nil'
      end

      if mailbox_ids.length > 100
        fail ArgumentError, 'invalid value for "mailbox_ids", number of items must be less than or equal to 100.'
      end

      @mailbox_ids = mailbox_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_pool_id Value to be assigned
    def mailbox_pool_id=(mailbox_pool_id)
      if mailbox_pool_id.nil?
        fail ArgumentError, 'mailbox_pool_id cannot be nil'
      end

      if mailbox_pool_id.to_s.length > 200
        fail ArgumentError, 'invalid value for "mailbox_pool_id", the character length must be smaller than or equal to 200.'
      end

      if mailbox_pool_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "mailbox_pool_id", the character length must be greater than or equal to 1.'
      end

      @mailbox_pool_id = mailbox_pool_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 200
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 200.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] steps Value to be assigned
    def steps=(steps)
      if steps.nil?
        fail ArgumentError, 'steps cannot be nil'
      end

      if steps.length > 50
        fail ArgumentError, 'invalid value for "steps", number of items must be less than or equal to 50.'
      end

      @steps = steps
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          audience_list_ids == o.audience_list_ids &&
          expected_version == o.expected_version &&
          mailbox_ids == o.mailbox_ids &&
          mailbox_pool_id == o.mailbox_pool_id &&
          name == o.name &&
          policy == o.policy &&
          scheduled_at == o.scheduled_at &&
          steps == o.steps
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [audience_list_ids, expected_version, mailbox_ids, mailbox_pool_id, name, policy, scheduled_at, steps].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
