=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPatchCampaignsByCampaignIdRequestPolicy < ApiModelBase
    attr_accessor :domain_quotas

    attr_accessor :mailbox_quotas

    attr_accessor :recipient_cooldown_ms

    attr_accessor :recipient_quotas

    attr_accessor :sending_windows

    attr_accessor :tenant_quotas

    attr_accessor :time_zone

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'domain_quotas' => :'domainQuotas',
        :'mailbox_quotas' => :'mailboxQuotas',
        :'recipient_cooldown_ms' => :'recipientCooldownMs',
        :'recipient_quotas' => :'recipientQuotas',
        :'sending_windows' => :'sendingWindows',
        :'tenant_quotas' => :'tenantQuotas',
        :'time_zone' => :'timeZone'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'domain_quotas' => :'Array<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner>',
        :'mailbox_quotas' => :'Array<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner>',
        :'recipient_cooldown_ms' => :'Integer',
        :'recipient_quotas' => :'Array<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner>',
        :'sending_windows' => :'Array<MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner>',
        :'tenant_quotas' => :'Array<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner>',
        :'time_zone' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPatchCampaignsByCampaignIdRequestPolicy` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPatchCampaignsByCampaignIdRequestPolicy`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'domain_quotas')
        if (value = attributes[:'domain_quotas']).is_a?(Array)
          self.domain_quotas = value
        end
      end

      if attributes.key?(:'mailbox_quotas')
        if (value = attributes[:'mailbox_quotas']).is_a?(Array)
          self.mailbox_quotas = value
        end
      end

      if attributes.key?(:'recipient_cooldown_ms')
        self.recipient_cooldown_ms = attributes[:'recipient_cooldown_ms']
      end

      if attributes.key?(:'recipient_quotas')
        if (value = attributes[:'recipient_quotas']).is_a?(Array)
          self.recipient_quotas = value
        end
      end

      if attributes.key?(:'sending_windows')
        if (value = attributes[:'sending_windows']).is_a?(Array)
          self.sending_windows = value
        end
      end

      if attributes.key?(:'tenant_quotas')
        if (value = attributes[:'tenant_quotas']).is_a?(Array)
          self.tenant_quotas = value
        end
      end

      if attributes.key?(:'time_zone')
        self.time_zone = attributes[:'time_zone']
      else
        self.time_zone = 'UTC'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@domain_quotas.nil? && @domain_quotas.length > 10
        invalid_properties.push('invalid value for "domain_quotas", number of items must be less than or equal to 10.')
      end

      if !@mailbox_quotas.nil? && @mailbox_quotas.length > 10
        invalid_properties.push('invalid value for "mailbox_quotas", number of items must be less than or equal to 10.')
      end

      if !@recipient_cooldown_ms.nil? && @recipient_cooldown_ms > 31536000000
        invalid_properties.push('invalid value for "recipient_cooldown_ms", must be smaller than or equal to 31536000000.')
      end

      if !@recipient_cooldown_ms.nil? && @recipient_cooldown_ms < 0
        invalid_properties.push('invalid value for "recipient_cooldown_ms", must be greater than or equal to 0.')
      end

      if !@recipient_quotas.nil? && @recipient_quotas.length > 10
        invalid_properties.push('invalid value for "recipient_quotas", number of items must be less than or equal to 10.')
      end

      if !@sending_windows.nil? && @sending_windows.length > 28
        invalid_properties.push('invalid value for "sending_windows", number of items must be less than or equal to 28.')
      end

      if !@tenant_quotas.nil? && @tenant_quotas.length > 10
        invalid_properties.push('invalid value for "tenant_quotas", number of items must be less than or equal to 10.')
      end

      if !@time_zone.nil? && @time_zone.to_s.length > 100
        invalid_properties.push('invalid value for "time_zone", the character length must be smaller than or equal to 100.')
      end

      if !@time_zone.nil? && @time_zone.to_s.length < 1
        invalid_properties.push('invalid value for "time_zone", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@domain_quotas.nil? && @domain_quotas.length > 10
      return false if !@mailbox_quotas.nil? && @mailbox_quotas.length > 10
      return false if !@recipient_cooldown_ms.nil? && @recipient_cooldown_ms > 31536000000
      return false if !@recipient_cooldown_ms.nil? && @recipient_cooldown_ms < 0
      return false if !@recipient_quotas.nil? && @recipient_quotas.length > 10
      return false if !@sending_windows.nil? && @sending_windows.length > 28
      return false if !@tenant_quotas.nil? && @tenant_quotas.length > 10
      return false if !@time_zone.nil? && @time_zone.to_s.length > 100
      return false if !@time_zone.nil? && @time_zone.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] domain_quotas Value to be assigned
    def domain_quotas=(domain_quotas)
      if domain_quotas.nil?
        fail ArgumentError, 'domain_quotas cannot be nil'
      end

      if domain_quotas.length > 10
        fail ArgumentError, 'invalid value for "domain_quotas", number of items must be less than or equal to 10.'
      end

      @domain_quotas = domain_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_quotas Value to be assigned
    def mailbox_quotas=(mailbox_quotas)
      if mailbox_quotas.nil?
        fail ArgumentError, 'mailbox_quotas cannot be nil'
      end

      if mailbox_quotas.length > 10
        fail ArgumentError, 'invalid value for "mailbox_quotas", number of items must be less than or equal to 10.'
      end

      @mailbox_quotas = mailbox_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] recipient_cooldown_ms Value to be assigned
    def recipient_cooldown_ms=(recipient_cooldown_ms)
      if recipient_cooldown_ms.nil?
        fail ArgumentError, 'recipient_cooldown_ms cannot be nil'
      end

      if recipient_cooldown_ms > 31536000000
        fail ArgumentError, 'invalid value for "recipient_cooldown_ms", must be smaller than or equal to 31536000000.'
      end

      if recipient_cooldown_ms < 0
        fail ArgumentError, 'invalid value for "recipient_cooldown_ms", must be greater than or equal to 0.'
      end

      @recipient_cooldown_ms = recipient_cooldown_ms
    end

    # Custom attribute writer method with validation
    # @param [Object] recipient_quotas Value to be assigned
    def recipient_quotas=(recipient_quotas)
      if recipient_quotas.nil?
        fail ArgumentError, 'recipient_quotas cannot be nil'
      end

      if recipient_quotas.length > 10
        fail ArgumentError, 'invalid value for "recipient_quotas", number of items must be less than or equal to 10.'
      end

      @recipient_quotas = recipient_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] sending_windows Value to be assigned
    def sending_windows=(sending_windows)
      if sending_windows.nil?
        fail ArgumentError, 'sending_windows cannot be nil'
      end

      if sending_windows.length > 28
        fail ArgumentError, 'invalid value for "sending_windows", number of items must be less than or equal to 28.'
      end

      @sending_windows = sending_windows
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_quotas Value to be assigned
    def tenant_quotas=(tenant_quotas)
      if tenant_quotas.nil?
        fail ArgumentError, 'tenant_quotas cannot be nil'
      end

      if tenant_quotas.length > 10
        fail ArgumentError, 'invalid value for "tenant_quotas", number of items must be less than or equal to 10.'
      end

      @tenant_quotas = tenant_quotas
    end

    # Custom attribute writer method with validation
    # @param [Object] time_zone Value to be assigned
    def time_zone=(time_zone)
      if time_zone.nil?
        fail ArgumentError, 'time_zone cannot be nil'
      end

      if time_zone.to_s.length > 100
        fail ArgumentError, 'invalid value for "time_zone", the character length must be smaller than or equal to 100.'
      end

      if time_zone.to_s.length < 1
        fail ArgumentError, 'invalid value for "time_zone", the character length must be greater than or equal to 1.'
      end

      @time_zone = time_zone
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          domain_quotas == o.domain_quotas &&
          mailbox_quotas == o.mailbox_quotas &&
          recipient_cooldown_ms == o.recipient_cooldown_ms &&
          recipient_quotas == o.recipient_quotas &&
          sending_windows == o.sending_windows &&
          tenant_quotas == o.tenant_quotas &&
          time_zone == o.time_zone
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [domain_quotas, mailbox_quotas, recipient_cooldown_ms, recipient_quotas, sending_windows, tenant_quotas, time_zone].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
