=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPostCadenceRunsPreflightResponse200 < ApiModelBase
    attr_accessor :audience_count

    attr_accessor :cadence_id

    attr_accessor :cadence_version

    attr_accessor :missing_variables

    attr_accessor :ready

    attr_accessor :required_variables

    attr_accessor :sender_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'audience_count' => :'audienceCount',
        :'cadence_id' => :'cadenceId',
        :'cadence_version' => :'cadenceVersion',
        :'missing_variables' => :'missingVariables',
        :'ready' => :'ready',
        :'required_variables' => :'requiredVariables',
        :'sender_count' => :'senderCount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'audience_count' => :'Float',
        :'cadence_id' => :'String',
        :'cadence_version' => :'Float',
        :'missing_variables' => :'Array<MailCadenceEnrollmentVariableGap>',
        :'ready' => :'Boolean',
        :'required_variables' => :'Array<String>',
        :'sender_count' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPostCadenceRunsPreflightResponse200` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPostCadenceRunsPreflightResponse200`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'audience_count')
        self.audience_count = attributes[:'audience_count']
      else
        self.audience_count = nil
      end

      if attributes.key?(:'cadence_id')
        self.cadence_id = attributes[:'cadence_id']
      else
        self.cadence_id = nil
      end

      if attributes.key?(:'cadence_version')
        self.cadence_version = attributes[:'cadence_version']
      else
        self.cadence_version = nil
      end

      if attributes.key?(:'missing_variables')
        if (value = attributes[:'missing_variables']).is_a?(Array)
          self.missing_variables = value
        end
      else
        self.missing_variables = nil
      end

      if attributes.key?(:'ready')
        self.ready = attributes[:'ready']
      else
        self.ready = nil
      end

      if attributes.key?(:'required_variables')
        if (value = attributes[:'required_variables']).is_a?(Array)
          self.required_variables = value
        end
      else
        self.required_variables = nil
      end

      if attributes.key?(:'sender_count')
        self.sender_count = attributes[:'sender_count']
      else
        self.sender_count = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @audience_count.nil?
        invalid_properties.push('invalid value for "audience_count", audience_count cannot be nil.')
      end

      if @cadence_id.nil?
        invalid_properties.push('invalid value for "cadence_id", cadence_id cannot be nil.')
      end

      if @cadence_version.nil?
        invalid_properties.push('invalid value for "cadence_version", cadence_version cannot be nil.')
      end

      if @missing_variables.nil?
        invalid_properties.push('invalid value for "missing_variables", missing_variables cannot be nil.')
      end

      if @ready.nil?
        invalid_properties.push('invalid value for "ready", ready cannot be nil.')
      end

      if @required_variables.nil?
        invalid_properties.push('invalid value for "required_variables", required_variables cannot be nil.')
      end

      if @sender_count.nil?
        invalid_properties.push('invalid value for "sender_count", sender_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @audience_count.nil?
      return false if @cadence_id.nil?
      return false if @cadence_version.nil?
      return false if @missing_variables.nil?
      return false if @ready.nil?
      return false if @required_variables.nil?
      return false if @sender_count.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] audience_count Value to be assigned
    def audience_count=(audience_count)
      if audience_count.nil?
        fail ArgumentError, 'audience_count cannot be nil'
      end

      @audience_count = audience_count
    end

    # Custom attribute writer method with validation
    # @param [Object] cadence_id Value to be assigned
    def cadence_id=(cadence_id)
      if cadence_id.nil?
        fail ArgumentError, 'cadence_id cannot be nil'
      end

      @cadence_id = cadence_id
    end

    # Custom attribute writer method with validation
    # @param [Object] cadence_version Value to be assigned
    def cadence_version=(cadence_version)
      if cadence_version.nil?
        fail ArgumentError, 'cadence_version cannot be nil'
      end

      @cadence_version = cadence_version
    end

    # Custom attribute writer method with validation
    # @param [Object] missing_variables Value to be assigned
    def missing_variables=(missing_variables)
      if missing_variables.nil?
        fail ArgumentError, 'missing_variables cannot be nil'
      end

      @missing_variables = missing_variables
    end

    # Custom attribute writer method with validation
    # @param [Object] ready Value to be assigned
    def ready=(ready)
      if ready.nil?
        fail ArgumentError, 'ready cannot be nil'
      end

      @ready = ready
    end

    # Custom attribute writer method with validation
    # @param [Object] required_variables Value to be assigned
    def required_variables=(required_variables)
      if required_variables.nil?
        fail ArgumentError, 'required_variables cannot be nil'
      end

      @required_variables = required_variables
    end

    # Custom attribute writer method with validation
    # @param [Object] sender_count Value to be assigned
    def sender_count=(sender_count)
      if sender_count.nil?
        fail ArgumentError, 'sender_count cannot be nil'
      end

      @sender_count = sender_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          audience_count == o.audience_count &&
          cadence_id == o.cadence_id &&
          cadence_version == o.cadence_version &&
          missing_variables == o.missing_variables &&
          ready == o.ready &&
          required_variables == o.required_variables &&
          sender_count == o.sender_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [audience_count, cadence_id, cadence_version, missing_variables, ready, required_variables, sender_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
