=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailGetOverviewResponse200Inbox < ApiModelBase
    attr_accessor :needs_reply

    attr_accessor :recent

    attr_accessor :unread

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'needs_reply' => :'needsReply',
        :'recent' => :'recent',
        :'unread' => :'unread'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'needs_reply' => :'Float',
        :'recent' => :'Array<MailInboxMessageRecord>',
        :'unread' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailGetOverviewResponse200Inbox` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailGetOverviewResponse200Inbox`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'needs_reply')
        self.needs_reply = attributes[:'needs_reply']
      else
        self.needs_reply = nil
      end

      if attributes.key?(:'recent')
        if (value = attributes[:'recent']).is_a?(Array)
          self.recent = value
        end
      else
        self.recent = nil
      end

      if attributes.key?(:'unread')
        self.unread = attributes[:'unread']
      else
        self.unread = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @needs_reply.nil?
        invalid_properties.push('invalid value for "needs_reply", needs_reply cannot be nil.')
      end

      if @recent.nil?
        invalid_properties.push('invalid value for "recent", recent cannot be nil.')
      end

      if @unread.nil?
        invalid_properties.push('invalid value for "unread", unread cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @needs_reply.nil?
      return false if @recent.nil?
      return false if @unread.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] needs_reply Value to be assigned
    def needs_reply=(needs_reply)
      if needs_reply.nil?
        fail ArgumentError, 'needs_reply cannot be nil'
      end

      @needs_reply = needs_reply
    end

    # Custom attribute writer method with validation
    # @param [Object] recent Value to be assigned
    def recent=(recent)
      if recent.nil?
        fail ArgumentError, 'recent cannot be nil'
      end

      @recent = recent
    end

    # Custom attribute writer method with validation
    # @param [Object] unread Value to be assigned
    def unread=(unread)
      if unread.nil?
        fail ArgumentError, 'unread cannot be nil'
      end

      @unread = unread
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          needs_reply == o.needs_reply &&
          recent == o.recent &&
          unread == o.unread
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [needs_reply, recent, unread].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
