=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailGetDeliverabilityResponse200 < ApiModelBase
    attr_accessor :health

    attr_accessor :mailboxes

    attr_accessor :pools

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'health' => :'health',
        :'mailboxes' => :'mailboxes',
        :'pools' => :'pools'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'health' => :'Array<MailMailboxHealthRecord>',
        :'mailboxes' => :'Array<MailMailboxRecord>',
        :'pools' => :'Array<MailGetDeliverabilityResponse200PoolsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailGetDeliverabilityResponse200` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailGetDeliverabilityResponse200`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'health')
        if (value = attributes[:'health']).is_a?(Array)
          self.health = value
        end
      else
        self.health = nil
      end

      if attributes.key?(:'mailboxes')
        if (value = attributes[:'mailboxes']).is_a?(Array)
          self.mailboxes = value
        end
      else
        self.mailboxes = nil
      end

      if attributes.key?(:'pools')
        if (value = attributes[:'pools']).is_a?(Array)
          self.pools = value
        end
      else
        self.pools = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @health.nil?
        invalid_properties.push('invalid value for "health", health cannot be nil.')
      end

      if @mailboxes.nil?
        invalid_properties.push('invalid value for "mailboxes", mailboxes cannot be nil.')
      end

      if @pools.nil?
        invalid_properties.push('invalid value for "pools", pools cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @health.nil?
      return false if @mailboxes.nil?
      return false if @pools.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] health Value to be assigned
    def health=(health)
      if health.nil?
        fail ArgumentError, 'health cannot be nil'
      end

      @health = health
    end

    # Custom attribute writer method with validation
    # @param [Object] mailboxes Value to be assigned
    def mailboxes=(mailboxes)
      if mailboxes.nil?
        fail ArgumentError, 'mailboxes cannot be nil'
      end

      @mailboxes = mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] pools Value to be assigned
    def pools=(pools)
      if pools.nil?
        fail ArgumentError, 'pools cannot be nil'
      end

      @pools = pools
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          health == o.health &&
          mailboxes == o.mailboxes &&
          pools == o.pools
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [health, mailboxes, pools].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
