=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailMessageRecord < ApiModelBase
    attr_accessor :accepted_at

    attr_accessor :attempt_count

    attr_accessor :bcc

    attr_accessor :cc

    attr_accessor :created_at

    attr_accessor :id

    attr_accessor :idempotency_key

    attr_accessor :internet_message_id

    attr_accessor :last_error

    attr_accessor :lease_expires_at

    attr_accessor :lease_owner

    attr_accessor :mailbox_id

    attr_accessor :metadata

    attr_accessor :next_attempt_at

    attr_accessor :parent_message_id

    attr_accessor :policy

    attr_accessor :provider_message_id

    attr_accessor :provider_thread_id

    attr_accessor :rendered

    attr_accessor :reply_to

    attr_accessor :scheduled_at

    attr_accessor :sequence_run_id

    attr_accessor :sequence_step_index

    attr_accessor :status

    attr_accessor :tenant_id

    attr_accessor :to

    attr_accessor :updated_at

    attr_accessor :variant_id

    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'accepted_at' => :'acceptedAt',
        :'attempt_count' => :'attemptCount',
        :'bcc' => :'bcc',
        :'cc' => :'cc',
        :'created_at' => :'createdAt',
        :'id' => :'id',
        :'idempotency_key' => :'idempotencyKey',
        :'internet_message_id' => :'internetMessageId',
        :'last_error' => :'lastError',
        :'lease_expires_at' => :'leaseExpiresAt',
        :'lease_owner' => :'leaseOwner',
        :'mailbox_id' => :'mailboxId',
        :'metadata' => :'metadata',
        :'next_attempt_at' => :'nextAttemptAt',
        :'parent_message_id' => :'parentMessageId',
        :'policy' => :'policy',
        :'provider_message_id' => :'providerMessageId',
        :'provider_thread_id' => :'providerThreadId',
        :'rendered' => :'rendered',
        :'reply_to' => :'replyTo',
        :'scheduled_at' => :'scheduledAt',
        :'sequence_run_id' => :'sequenceRunId',
        :'sequence_step_index' => :'sequenceStepIndex',
        :'status' => :'status',
        :'tenant_id' => :'tenantId',
        :'to' => :'to',
        :'updated_at' => :'updatedAt',
        :'variant_id' => :'variantId',
        :'version' => :'version'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'accepted_at' => :'Time',
        :'attempt_count' => :'Float',
        :'bcc' => :'Array<MailMailAddress>',
        :'cc' => :'Array<MailMailAddress>',
        :'created_at' => :'Time',
        :'id' => :'String',
        :'idempotency_key' => :'String',
        :'internet_message_id' => :'String',
        :'last_error' => :'MailProviderFailure',
        :'lease_expires_at' => :'Time',
        :'lease_owner' => :'String',
        :'mailbox_id' => :'String',
        :'metadata' => :'Object',
        :'next_attempt_at' => :'Time',
        :'parent_message_id' => :'String',
        :'policy' => :'MailMessagePolicy',
        :'provider_message_id' => :'String',
        :'provider_thread_id' => :'String',
        :'rendered' => :'MailRenderedMessage',
        :'reply_to' => :'MailMailAddress',
        :'scheduled_at' => :'Time',
        :'sequence_run_id' => :'String',
        :'sequence_step_index' => :'Float',
        :'status' => :'String',
        :'tenant_id' => :'String',
        :'to' => :'Array<MailMailAddress>',
        :'updated_at' => :'Time',
        :'variant_id' => :'String',
        :'version' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailMessageRecord` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailMessageRecord`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'accepted_at')
        self.accepted_at = attributes[:'accepted_at']
      end

      if attributes.key?(:'attempt_count')
        self.attempt_count = attributes[:'attempt_count']
      else
        self.attempt_count = nil
      end

      if attributes.key?(:'bcc')
        if (value = attributes[:'bcc']).is_a?(Array)
          self.bcc = value
        end
      else
        self.bcc = nil
      end

      if attributes.key?(:'cc')
        if (value = attributes[:'cc']).is_a?(Array)
          self.cc = value
        end
      else
        self.cc = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      else
        self.idempotency_key = nil
      end

      if attributes.key?(:'internet_message_id')
        self.internet_message_id = attributes[:'internet_message_id']
      end

      if attributes.key?(:'last_error')
        self.last_error = attributes[:'last_error']
      end

      if attributes.key?(:'lease_expires_at')
        self.lease_expires_at = attributes[:'lease_expires_at']
      end

      if attributes.key?(:'lease_owner')
        self.lease_owner = attributes[:'lease_owner']
      end

      if attributes.key?(:'mailbox_id')
        self.mailbox_id = attributes[:'mailbox_id']
      else
        self.mailbox_id = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'next_attempt_at')
        self.next_attempt_at = attributes[:'next_attempt_at']
      else
        self.next_attempt_at = nil
      end

      if attributes.key?(:'parent_message_id')
        self.parent_message_id = attributes[:'parent_message_id']
      end

      if attributes.key?(:'policy')
        self.policy = attributes[:'policy']
      else
        self.policy = nil
      end

      if attributes.key?(:'provider_message_id')
        self.provider_message_id = attributes[:'provider_message_id']
      end

      if attributes.key?(:'provider_thread_id')
        self.provider_thread_id = attributes[:'provider_thread_id']
      end

      if attributes.key?(:'rendered')
        self.rendered = attributes[:'rendered']
      else
        self.rendered = nil
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      else
        self.reply_to = nil
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      else
        self.scheduled_at = nil
      end

      if attributes.key?(:'sequence_run_id')
        self.sequence_run_id = attributes[:'sequence_run_id']
      end

      if attributes.key?(:'sequence_step_index')
        self.sequence_step_index = attributes[:'sequence_step_index']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'to')
        if (value = attributes[:'to']).is_a?(Array)
          self.to = value
        end
      else
        self.to = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'variant_id')
        self.variant_id = attributes[:'variant_id']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      else
        self.version = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @attempt_count.nil?
        invalid_properties.push('invalid value for "attempt_count", attempt_count cannot be nil.')
      end

      if @bcc.nil?
        invalid_properties.push('invalid value for "bcc", bcc cannot be nil.')
      end

      if @cc.nil?
        invalid_properties.push('invalid value for "cc", cc cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @idempotency_key.nil?
        invalid_properties.push('invalid value for "idempotency_key", idempotency_key cannot be nil.')
      end

      if @mailbox_id.nil?
        invalid_properties.push('invalid value for "mailbox_id", mailbox_id cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @next_attempt_at.nil?
        invalid_properties.push('invalid value for "next_attempt_at", next_attempt_at cannot be nil.')
      end

      if @policy.nil?
        invalid_properties.push('invalid value for "policy", policy cannot be nil.')
      end

      if @rendered.nil?
        invalid_properties.push('invalid value for "rendered", rendered cannot be nil.')
      end

      if @reply_to.nil?
        invalid_properties.push('invalid value for "reply_to", reply_to cannot be nil.')
      end

      if @scheduled_at.nil?
        invalid_properties.push('invalid value for "scheduled_at", scheduled_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @version.nil?
        invalid_properties.push('invalid value for "version", version cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @attempt_count.nil?
      return false if @bcc.nil?
      return false if @cc.nil?
      return false if @created_at.nil?
      return false if @id.nil?
      return false if @idempotency_key.nil?
      return false if @mailbox_id.nil?
      return false if @metadata.nil?
      return false if @next_attempt_at.nil?
      return false if @policy.nil?
      return false if @rendered.nil?
      return false if @reply_to.nil?
      return false if @scheduled_at.nil?
      return false if @status.nil?
      return false if @tenant_id.nil?
      return false if @to.nil?
      return false if @updated_at.nil?
      return false if @version.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] attempt_count Value to be assigned
    def attempt_count=(attempt_count)
      if attempt_count.nil?
        fail ArgumentError, 'attempt_count cannot be nil'
      end

      @attempt_count = attempt_count
    end

    # Custom attribute writer method with validation
    # @param [Object] bcc Value to be assigned
    def bcc=(bcc)
      if bcc.nil?
        fail ArgumentError, 'bcc cannot be nil'
      end

      @bcc = bcc
    end

    # Custom attribute writer method with validation
    # @param [Object] cc Value to be assigned
    def cc=(cc)
      if cc.nil?
        fail ArgumentError, 'cc cannot be nil'
      end

      @cc = cc
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      @idempotency_key = idempotency_key
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_id Value to be assigned
    def mailbox_id=(mailbox_id)
      if mailbox_id.nil?
        fail ArgumentError, 'mailbox_id cannot be nil'
      end

      @mailbox_id = mailbox_id
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] next_attempt_at Value to be assigned
    def next_attempt_at=(next_attempt_at)
      if next_attempt_at.nil?
        fail ArgumentError, 'next_attempt_at cannot be nil'
      end

      @next_attempt_at = next_attempt_at
    end

    # Custom attribute writer method with validation
    # @param [Object] policy Value to be assigned
    def policy=(policy)
      if policy.nil?
        fail ArgumentError, 'policy cannot be nil'
      end

      @policy = policy
    end

    # Custom attribute writer method with validation
    # @param [Object] rendered Value to be assigned
    def rendered=(rendered)
      if rendered.nil?
        fail ArgumentError, 'rendered cannot be nil'
      end

      @rendered = rendered
    end

    # Custom attribute writer method with validation
    # @param [Object] reply_to Value to be assigned
    def reply_to=(reply_to)
      if reply_to.nil?
        fail ArgumentError, 'reply_to cannot be nil'
      end

      @reply_to = reply_to
    end

    # Custom attribute writer method with validation
    # @param [Object] scheduled_at Value to be assigned
    def scheduled_at=(scheduled_at)
      if scheduled_at.nil?
        fail ArgumentError, 'scheduled_at cannot be nil'
      end

      @scheduled_at = scheduled_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      @to = to
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] version Value to be assigned
    def version=(version)
      if version.nil?
        fail ArgumentError, 'version cannot be nil'
      end

      @version = version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          accepted_at == o.accepted_at &&
          attempt_count == o.attempt_count &&
          bcc == o.bcc &&
          cc == o.cc &&
          created_at == o.created_at &&
          id == o.id &&
          idempotency_key == o.idempotency_key &&
          internet_message_id == o.internet_message_id &&
          last_error == o.last_error &&
          lease_expires_at == o.lease_expires_at &&
          lease_owner == o.lease_owner &&
          mailbox_id == o.mailbox_id &&
          metadata == o.metadata &&
          next_attempt_at == o.next_attempt_at &&
          parent_message_id == o.parent_message_id &&
          policy == o.policy &&
          provider_message_id == o.provider_message_id &&
          provider_thread_id == o.provider_thread_id &&
          rendered == o.rendered &&
          reply_to == o.reply_to &&
          scheduled_at == o.scheduled_at &&
          sequence_run_id == o.sequence_run_id &&
          sequence_step_index == o.sequence_step_index &&
          status == o.status &&
          tenant_id == o.tenant_id &&
          to == o.to &&
          updated_at == o.updated_at &&
          variant_id == o.variant_id &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [accepted_at, attempt_count, bcc, cc, created_at, id, idempotency_key, internet_message_id, last_error, lease_expires_at, lease_owner, mailbox_id, metadata, next_attempt_at, parent_message_id, policy, provider_message_id, provider_thread_id, rendered, reply_to, scheduled_at, sequence_run_id, sequence_step_index, status, tenant_id, to, updated_at, variant_id, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
