=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailGetChannelsResponse200Email < ApiModelBase
    attr_accessor :active_connections

    attr_accessor :active_mailboxes

    attr_accessor :configured

    attr_accessor :reply_sync_enabled

    attr_accessor :sequence_supported

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'active_connections' => :'activeConnections',
        :'active_mailboxes' => :'activeMailboxes',
        :'configured' => :'configured',
        :'reply_sync_enabled' => :'replySyncEnabled',
        :'sequence_supported' => :'sequenceSupported'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'active_connections' => :'Float',
        :'active_mailboxes' => :'Float',
        :'configured' => :'Boolean',
        :'reply_sync_enabled' => :'Boolean',
        :'sequence_supported' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailGetChannelsResponse200Email` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailGetChannelsResponse200Email`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'active_connections')
        self.active_connections = attributes[:'active_connections']
      else
        self.active_connections = nil
      end

      if attributes.key?(:'active_mailboxes')
        self.active_mailboxes = attributes[:'active_mailboxes']
      else
        self.active_mailboxes = nil
      end

      if attributes.key?(:'configured')
        self.configured = attributes[:'configured']
      else
        self.configured = nil
      end

      if attributes.key?(:'reply_sync_enabled')
        self.reply_sync_enabled = attributes[:'reply_sync_enabled']
      else
        self.reply_sync_enabled = nil
      end

      if attributes.key?(:'sequence_supported')
        self.sequence_supported = attributes[:'sequence_supported']
      else
        self.sequence_supported = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @active_connections.nil?
        invalid_properties.push('invalid value for "active_connections", active_connections cannot be nil.')
      end

      if @active_mailboxes.nil?
        invalid_properties.push('invalid value for "active_mailboxes", active_mailboxes cannot be nil.')
      end

      if @configured.nil?
        invalid_properties.push('invalid value for "configured", configured cannot be nil.')
      end

      if @reply_sync_enabled.nil?
        invalid_properties.push('invalid value for "reply_sync_enabled", reply_sync_enabled cannot be nil.')
      end

      if @sequence_supported.nil?
        invalid_properties.push('invalid value for "sequence_supported", sequence_supported cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @active_connections.nil?
      return false if @active_mailboxes.nil?
      return false if @configured.nil?
      return false if @reply_sync_enabled.nil?
      return false if @sequence_supported.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] active_connections Value to be assigned
    def active_connections=(active_connections)
      if active_connections.nil?
        fail ArgumentError, 'active_connections cannot be nil'
      end

      @active_connections = active_connections
    end

    # Custom attribute writer method with validation
    # @param [Object] active_mailboxes Value to be assigned
    def active_mailboxes=(active_mailboxes)
      if active_mailboxes.nil?
        fail ArgumentError, 'active_mailboxes cannot be nil'
      end

      @active_mailboxes = active_mailboxes
    end

    # Custom attribute writer method with validation
    # @param [Object] configured Value to be assigned
    def configured=(configured)
      if configured.nil?
        fail ArgumentError, 'configured cannot be nil'
      end

      @configured = configured
    end

    # Custom attribute writer method with validation
    # @param [Object] reply_sync_enabled Value to be assigned
    def reply_sync_enabled=(reply_sync_enabled)
      if reply_sync_enabled.nil?
        fail ArgumentError, 'reply_sync_enabled cannot be nil'
      end

      @reply_sync_enabled = reply_sync_enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] sequence_supported Value to be assigned
    def sequence_supported=(sequence_supported)
      if sequence_supported.nil?
        fail ArgumentError, 'sequence_supported cannot be nil'
      end

      @sequence_supported = sequence_supported
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          active_connections == o.active_connections &&
          active_mailboxes == o.active_mailboxes &&
          configured == o.configured &&
          reply_sync_enabled == o.reply_sync_enabled &&
          sequence_supported == o.sequence_supported
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [active_connections, active_mailboxes, configured, reply_sync_enabled, sequence_supported].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
