=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPostMailboxesManualRequestSmtp < ApiModelBase
    attr_accessor :host

    attr_accessor :message_id_domain

    attr_accessor :password

    # Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
    attr_accessor :port

    attr_accessor :security

    attr_accessor :server_name

    attr_accessor :tls_ca

    attr_accessor :username

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'host' => :'host',
        :'message_id_domain' => :'messageIdDomain',
        :'password' => :'password',
        :'port' => :'port',
        :'security' => :'security',
        :'server_name' => :'serverName',
        :'tls_ca' => :'tlsCa',
        :'username' => :'username'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'host' => :'String',
        :'message_id_domain' => :'String',
        :'password' => :'String',
        :'port' => :'Integer',
        :'security' => :'String',
        :'server_name' => :'String',
        :'tls_ca' => :'String',
        :'username' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPostMailboxesManualRequestSmtp` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPostMailboxesManualRequestSmtp`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'host')
        self.host = attributes[:'host']
      else
        self.host = nil
      end

      if attributes.key?(:'message_id_domain')
        self.message_id_domain = attributes[:'message_id_domain']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      else
        self.password = nil
      end

      if attributes.key?(:'port')
        self.port = attributes[:'port']
      else
        self.port = nil
      end

      if attributes.key?(:'security')
        self.security = attributes[:'security']
      else
        self.security = nil
      end

      if attributes.key?(:'server_name')
        self.server_name = attributes[:'server_name']
      end

      if attributes.key?(:'tls_ca')
        self.tls_ca = attributes[:'tls_ca']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      else
        self.username = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @host.nil?
        invalid_properties.push('invalid value for "host", host cannot be nil.')
      end

      if @host.to_s.length > 253
        invalid_properties.push('invalid value for "host", the character length must be smaller than or equal to 253.')
      end

      if @host.to_s.length < 1
        invalid_properties.push('invalid value for "host", the character length must be greater than or equal to 1.')
      end

      if !@message_id_domain.nil? && @message_id_domain.to_s.length > 253
        invalid_properties.push('invalid value for "message_id_domain", the character length must be smaller than or equal to 253.')
      end

      if !@message_id_domain.nil? && @message_id_domain.to_s.length < 1
        invalid_properties.push('invalid value for "message_id_domain", the character length must be greater than or equal to 1.')
      end

      if @password.nil?
        invalid_properties.push('invalid value for "password", password cannot be nil.')
      end

      if @password.to_s.length > 4096
        invalid_properties.push('invalid value for "password", the character length must be smaller than or equal to 4096.')
      end

      if @password.to_s.length < 1
        invalid_properties.push('invalid value for "password", the character length must be greater than or equal to 1.')
      end

      if @port.nil?
        invalid_properties.push('invalid value for "port", port cannot be nil.')
      end

      if @port > 65535
        invalid_properties.push('invalid value for "port", must be smaller than or equal to 65535.')
      end

      if @port < 1
        invalid_properties.push('invalid value for "port", must be greater than or equal to 1.')
      end

      if @security.nil?
        invalid_properties.push('invalid value for "security", security cannot be nil.')
      end

      if !@server_name.nil? && @server_name.to_s.length > 253
        invalid_properties.push('invalid value for "server_name", the character length must be smaller than or equal to 253.')
      end

      if !@server_name.nil? && @server_name.to_s.length < 1
        invalid_properties.push('invalid value for "server_name", the character length must be greater than or equal to 1.')
      end

      if !@tls_ca.nil? && @tls_ca.to_s.length > 100000
        invalid_properties.push('invalid value for "tls_ca", the character length must be smaller than or equal to 100000.')
      end

      if !@tls_ca.nil? && @tls_ca.to_s.length < 1
        invalid_properties.push('invalid value for "tls_ca", the character length must be greater than or equal to 1.')
      end

      if @username.nil?
        invalid_properties.push('invalid value for "username", username cannot be nil.')
      end

      if @username.to_s.length > 500
        invalid_properties.push('invalid value for "username", the character length must be smaller than or equal to 500.')
      end

      if @username.to_s.length < 1
        invalid_properties.push('invalid value for "username", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @host.nil?
      return false if @host.to_s.length > 253
      return false if @host.to_s.length < 1
      return false if !@message_id_domain.nil? && @message_id_domain.to_s.length > 253
      return false if !@message_id_domain.nil? && @message_id_domain.to_s.length < 1
      return false if @password.nil?
      return false if @password.to_s.length > 4096
      return false if @password.to_s.length < 1
      return false if @port.nil?
      return false if @port > 65535
      return false if @port < 1
      return false if @security.nil?
      security_validator = EnumAttributeValidator.new('String', ["tls", "starttls", "plain"])
      return false unless security_validator.valid?(@security)
      return false if !@server_name.nil? && @server_name.to_s.length > 253
      return false if !@server_name.nil? && @server_name.to_s.length < 1
      return false if !@tls_ca.nil? && @tls_ca.to_s.length > 100000
      return false if !@tls_ca.nil? && @tls_ca.to_s.length < 1
      return false if @username.nil?
      return false if @username.to_s.length > 500
      return false if @username.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] host Value to be assigned
    def host=(host)
      if host.nil?
        fail ArgumentError, 'host cannot be nil'
      end

      if host.to_s.length > 253
        fail ArgumentError, 'invalid value for "host", the character length must be smaller than or equal to 253.'
      end

      if host.to_s.length < 1
        fail ArgumentError, 'invalid value for "host", the character length must be greater than or equal to 1.'
      end

      @host = host
    end

    # Custom attribute writer method with validation
    # @param [Object] message_id_domain Value to be assigned
    def message_id_domain=(message_id_domain)
      if message_id_domain.nil?
        fail ArgumentError, 'message_id_domain cannot be nil'
      end

      if message_id_domain.to_s.length > 253
        fail ArgumentError, 'invalid value for "message_id_domain", the character length must be smaller than or equal to 253.'
      end

      if message_id_domain.to_s.length < 1
        fail ArgumentError, 'invalid value for "message_id_domain", the character length must be greater than or equal to 1.'
      end

      @message_id_domain = message_id_domain
    end

    # Custom attribute writer method with validation
    # @param [Object] password Value to be assigned
    def password=(password)
      if password.nil?
        fail ArgumentError, 'password cannot be nil'
      end

      if password.to_s.length > 4096
        fail ArgumentError, 'invalid value for "password", the character length must be smaller than or equal to 4096.'
      end

      if password.to_s.length < 1
        fail ArgumentError, 'invalid value for "password", the character length must be greater than or equal to 1.'
      end

      @password = password
    end

    # Custom attribute writer method with validation
    # @param [Object] port Value to be assigned
    def port=(port)
      if port.nil?
        fail ArgumentError, 'port cannot be nil'
      end

      if port > 65535
        fail ArgumentError, 'invalid value for "port", must be smaller than or equal to 65535.'
      end

      if port < 1
        fail ArgumentError, 'invalid value for "port", must be greater than or equal to 1.'
      end

      @port = port
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] security Object to be assigned
    def security=(security)
      validator = EnumAttributeValidator.new('String', ["tls", "starttls", "plain"])
      unless validator.valid?(security)
        fail ArgumentError, "invalid value for \"security\", must be one of #{validator.allowable_values}."
      end
      @security = security
    end

    # Custom attribute writer method with validation
    # @param [Object] server_name Value to be assigned
    def server_name=(server_name)
      if server_name.nil?
        fail ArgumentError, 'server_name cannot be nil'
      end

      if server_name.to_s.length > 253
        fail ArgumentError, 'invalid value for "server_name", the character length must be smaller than or equal to 253.'
      end

      if server_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "server_name", the character length must be greater than or equal to 1.'
      end

      @server_name = server_name
    end

    # Custom attribute writer method with validation
    # @param [Object] tls_ca Value to be assigned
    def tls_ca=(tls_ca)
      if tls_ca.nil?
        fail ArgumentError, 'tls_ca cannot be nil'
      end

      if tls_ca.to_s.length > 100000
        fail ArgumentError, 'invalid value for "tls_ca", the character length must be smaller than or equal to 100000.'
      end

      if tls_ca.to_s.length < 1
        fail ArgumentError, 'invalid value for "tls_ca", the character length must be greater than or equal to 1.'
      end

      @tls_ca = tls_ca
    end

    # Custom attribute writer method with validation
    # @param [Object] username Value to be assigned
    def username=(username)
      if username.nil?
        fail ArgumentError, 'username cannot be nil'
      end

      if username.to_s.length > 500
        fail ArgumentError, 'invalid value for "username", the character length must be smaller than or equal to 500.'
      end

      if username.to_s.length < 1
        fail ArgumentError, 'invalid value for "username", the character length must be greater than or equal to 1.'
      end

      @username = username
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          host == o.host &&
          message_id_domain == o.message_id_domain &&
          password == o.password &&
          port == o.port &&
          security == o.security &&
          server_name == o.server_name &&
          tls_ca == o.tls_ca &&
          username == o.username
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [host, message_id_domain, password, port, security, server_name, tls_ca, username].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
