=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailCadenceStopConditions < ApiModelBase
    attr_accessor :meeting_booked

    attr_accessor :negative_reply

    attr_accessor :out_of_office

    attr_accessor :positive_reply

    attr_accessor :unknown_human_reply

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'meeting_booked' => :'meetingBooked',
        :'negative_reply' => :'negativeReply',
        :'out_of_office' => :'outOfOffice',
        :'positive_reply' => :'positiveReply',
        :'unknown_human_reply' => :'unknownHumanReply'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'meeting_booked' => :'String',
        :'negative_reply' => :'String',
        :'out_of_office' => :'String',
        :'positive_reply' => :'String',
        :'unknown_human_reply' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailCadenceStopConditions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailCadenceStopConditions`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'meeting_booked')
        self.meeting_booked = attributes[:'meeting_booked']
      else
        self.meeting_booked = nil
      end

      if attributes.key?(:'negative_reply')
        self.negative_reply = attributes[:'negative_reply']
      else
        self.negative_reply = nil
      end

      if attributes.key?(:'out_of_office')
        self.out_of_office = attributes[:'out_of_office']
      else
        self.out_of_office = nil
      end

      if attributes.key?(:'positive_reply')
        self.positive_reply = attributes[:'positive_reply']
      else
        self.positive_reply = nil
      end

      if attributes.key?(:'unknown_human_reply')
        self.unknown_human_reply = attributes[:'unknown_human_reply']
      else
        self.unknown_human_reply = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @meeting_booked.nil?
        invalid_properties.push('invalid value for "meeting_booked", meeting_booked cannot be nil.')
      end

      if @negative_reply.nil?
        invalid_properties.push('invalid value for "negative_reply", negative_reply cannot be nil.')
      end

      if @out_of_office.nil?
        invalid_properties.push('invalid value for "out_of_office", out_of_office cannot be nil.')
      end

      if @positive_reply.nil?
        invalid_properties.push('invalid value for "positive_reply", positive_reply cannot be nil.')
      end

      if @unknown_human_reply.nil?
        invalid_properties.push('invalid value for "unknown_human_reply", unknown_human_reply cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @meeting_booked.nil?
      return false if @negative_reply.nil?
      return false if @out_of_office.nil?
      return false if @positive_reply.nil?
      return false if @unknown_human_reply.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] meeting_booked Value to be assigned
    def meeting_booked=(meeting_booked)
      if meeting_booked.nil?
        fail ArgumentError, 'meeting_booked cannot be nil'
      end

      @meeting_booked = meeting_booked
    end

    # Custom attribute writer method with validation
    # @param [Object] negative_reply Value to be assigned
    def negative_reply=(negative_reply)
      if negative_reply.nil?
        fail ArgumentError, 'negative_reply cannot be nil'
      end

      @negative_reply = negative_reply
    end

    # Custom attribute writer method with validation
    # @param [Object] out_of_office Value to be assigned
    def out_of_office=(out_of_office)
      if out_of_office.nil?
        fail ArgumentError, 'out_of_office cannot be nil'
      end

      @out_of_office = out_of_office
    end

    # Custom attribute writer method with validation
    # @param [Object] positive_reply Value to be assigned
    def positive_reply=(positive_reply)
      if positive_reply.nil?
        fail ArgumentError, 'positive_reply cannot be nil'
      end

      @positive_reply = positive_reply
    end

    # Custom attribute writer method with validation
    # @param [Object] unknown_human_reply Value to be assigned
    def unknown_human_reply=(unknown_human_reply)
      if unknown_human_reply.nil?
        fail ArgumentError, 'unknown_human_reply cannot be nil'
      end

      @unknown_human_reply = unknown_human_reply
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          meeting_booked == o.meeting_booked &&
          negative_reply == o.negative_reply &&
          out_of_office == o.out_of_office &&
          positive_reply == o.positive_reply &&
          unknown_human_reply == o.unknown_human_reply
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [meeting_booked, negative_reply, out_of_office, positive_reply, unknown_human_reply].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
