=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailGetChannelsResponse200Sms < ApiModelBase
    attr_accessor :configured

    attr_accessor :consent_required

    attr_accessor :cost_ceiling_required

    attr_accessor :execution_enabled

    attr_accessor :sequence_supported

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'configured' => :'configured',
        :'consent_required' => :'consentRequired',
        :'cost_ceiling_required' => :'costCeilingRequired',
        :'execution_enabled' => :'executionEnabled',
        :'sequence_supported' => :'sequenceSupported'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'configured' => :'Boolean',
        :'consent_required' => :'Boolean',
        :'cost_ceiling_required' => :'Boolean',
        :'execution_enabled' => :'Boolean',
        :'sequence_supported' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailGetChannelsResponse200Sms` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailGetChannelsResponse200Sms`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'configured')
        self.configured = attributes[:'configured']
      else
        self.configured = nil
      end

      if attributes.key?(:'consent_required')
        self.consent_required = attributes[:'consent_required']
      else
        self.consent_required = nil
      end

      if attributes.key?(:'cost_ceiling_required')
        self.cost_ceiling_required = attributes[:'cost_ceiling_required']
      else
        self.cost_ceiling_required = nil
      end

      if attributes.key?(:'execution_enabled')
        self.execution_enabled = attributes[:'execution_enabled']
      else
        self.execution_enabled = nil
      end

      if attributes.key?(:'sequence_supported')
        self.sequence_supported = attributes[:'sequence_supported']
      else
        self.sequence_supported = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @configured.nil?
        invalid_properties.push('invalid value for "configured", configured cannot be nil.')
      end

      if @consent_required.nil?
        invalid_properties.push('invalid value for "consent_required", consent_required cannot be nil.')
      end

      if @cost_ceiling_required.nil?
        invalid_properties.push('invalid value for "cost_ceiling_required", cost_ceiling_required cannot be nil.')
      end

      if @execution_enabled.nil?
        invalid_properties.push('invalid value for "execution_enabled", execution_enabled cannot be nil.')
      end

      if @sequence_supported.nil?
        invalid_properties.push('invalid value for "sequence_supported", sequence_supported cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @configured.nil?
      return false if @consent_required.nil?
      return false if @cost_ceiling_required.nil?
      return false if @execution_enabled.nil?
      return false if @sequence_supported.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] configured Value to be assigned
    def configured=(configured)
      if configured.nil?
        fail ArgumentError, 'configured cannot be nil'
      end

      @configured = configured
    end

    # Custom attribute writer method with validation
    # @param [Object] consent_required Value to be assigned
    def consent_required=(consent_required)
      if consent_required.nil?
        fail ArgumentError, 'consent_required cannot be nil'
      end

      @consent_required = consent_required
    end

    # Custom attribute writer method with validation
    # @param [Object] cost_ceiling_required Value to be assigned
    def cost_ceiling_required=(cost_ceiling_required)
      if cost_ceiling_required.nil?
        fail ArgumentError, 'cost_ceiling_required cannot be nil'
      end

      @cost_ceiling_required = cost_ceiling_required
    end

    # Custom attribute writer method with validation
    # @param [Object] execution_enabled Value to be assigned
    def execution_enabled=(execution_enabled)
      if execution_enabled.nil?
        fail ArgumentError, 'execution_enabled cannot be nil'
      end

      @execution_enabled = execution_enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] sequence_supported Value to be assigned
    def sequence_supported=(sequence_supported)
      if sequence_supported.nil?
        fail ArgumentError, 'sequence_supported cannot be nil'
      end

      @sequence_supported = sequence_supported
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          configured == o.configured &&
          consent_required == o.consent_required &&
          cost_ceiling_required == o.cost_ceiling_required &&
          execution_enabled == o.execution_enabled &&
          sequence_supported == o.sequence_supported
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [configured, consent_required, cost_ceiling_required, execution_enabled, sequence_supported].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
