=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailPostCadenceCampaignsByCampaignIdStateResponse200AnyOf < ApiModelBase
    attr_accessor :action

    attr_accessor :campaign_id

    attr_accessor :changed_runs

    attr_accessor :eligible_runs

    attr_accessor :total_runs

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'action' => :'action',
        :'campaign_id' => :'campaignId',
        :'changed_runs' => :'changedRuns',
        :'eligible_runs' => :'eligibleRuns',
        :'total_runs' => :'totalRuns'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'action' => :'String',
        :'campaign_id' => :'String',
        :'changed_runs' => :'Array<MailCadenceRunRecord>',
        :'eligible_runs' => :'Float',
        :'total_runs' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailPostCadenceCampaignsByCampaignIdStateResponse200AnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailPostCadenceCampaignsByCampaignIdStateResponse200AnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      else
        self.action = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      else
        self.campaign_id = nil
      end

      if attributes.key?(:'changed_runs')
        if (value = attributes[:'changed_runs']).is_a?(Array)
          self.changed_runs = value
        end
      else
        self.changed_runs = nil
      end

      if attributes.key?(:'eligible_runs')
        self.eligible_runs = attributes[:'eligible_runs']
      else
        self.eligible_runs = nil
      end

      if attributes.key?(:'total_runs')
        self.total_runs = attributes[:'total_runs']
      else
        self.total_runs = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @action.nil?
        invalid_properties.push('invalid value for "action", action cannot be nil.')
      end

      if @campaign_id.nil?
        invalid_properties.push('invalid value for "campaign_id", campaign_id cannot be nil.')
      end

      if @changed_runs.nil?
        invalid_properties.push('invalid value for "changed_runs", changed_runs cannot be nil.')
      end

      if @eligible_runs.nil?
        invalid_properties.push('invalid value for "eligible_runs", eligible_runs cannot be nil.')
      end

      if @total_runs.nil?
        invalid_properties.push('invalid value for "total_runs", total_runs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @action.nil?
      return false if @campaign_id.nil?
      return false if @changed_runs.nil?
      return false if @eligible_runs.nil?
      return false if @total_runs.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] action Value to be assigned
    def action=(action)
      if action.nil?
        fail ArgumentError, 'action cannot be nil'
      end

      @action = action
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign_id Value to be assigned
    def campaign_id=(campaign_id)
      if campaign_id.nil?
        fail ArgumentError, 'campaign_id cannot be nil'
      end

      @campaign_id = campaign_id
    end

    # Custom attribute writer method with validation
    # @param [Object] changed_runs Value to be assigned
    def changed_runs=(changed_runs)
      if changed_runs.nil?
        fail ArgumentError, 'changed_runs cannot be nil'
      end

      @changed_runs = changed_runs
    end

    # Custom attribute writer method with validation
    # @param [Object] eligible_runs Value to be assigned
    def eligible_runs=(eligible_runs)
      if eligible_runs.nil?
        fail ArgumentError, 'eligible_runs cannot be nil'
      end

      @eligible_runs = eligible_runs
    end

    # Custom attribute writer method with validation
    # @param [Object] total_runs Value to be assigned
    def total_runs=(total_runs)
      if total_runs.nil?
        fail ArgumentError, 'total_runs cannot be nil'
      end

      @total_runs = total_runs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          action == o.action &&
          campaign_id == o.campaign_id &&
          changed_runs == o.changed_runs &&
          eligible_runs == o.eligible_runs &&
          total_runs == o.total_runs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [action, campaign_id, changed_runs, eligible_runs, total_runs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
