=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class MailMessageTemplateVersion < ApiModelBase
    attr_accessor :body

    attr_accessor :channel

    attr_accessor :created_at

    attr_accessor :created_by_actor_id

    attr_accessor :id

    attr_accessor :name

    attr_accessor :status

    attr_accessor :subject

    attr_accessor :tenant_id

    attr_accessor :variables

    attr_accessor :version

    attr_accessor :whatsapp_approval

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'body' => :'body',
        :'channel' => :'channel',
        :'created_at' => :'createdAt',
        :'created_by_actor_id' => :'createdByActorId',
        :'id' => :'id',
        :'name' => :'name',
        :'status' => :'status',
        :'subject' => :'subject',
        :'tenant_id' => :'tenantId',
        :'variables' => :'variables',
        :'version' => :'version',
        :'whatsapp_approval' => :'whatsappApproval'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'body' => :'String',
        :'channel' => :'String',
        :'created_at' => :'Time',
        :'created_by_actor_id' => :'String',
        :'id' => :'String',
        :'name' => :'String',
        :'status' => :'String',
        :'subject' => :'String',
        :'tenant_id' => :'String',
        :'variables' => :'Array<String>',
        :'version' => :'Float',
        :'whatsapp_approval' => :'MailMessageTemplateVersionWhatsappApproval'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::MailMessageTemplateVersion` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::MailMessageTemplateVersion`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      else
        self.body = nil
      end

      if attributes.key?(:'channel')
        self.channel = attributes[:'channel']
      else
        self.channel = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'created_by_actor_id')
        self.created_by_actor_id = attributes[:'created_by_actor_id']
      else
        self.created_by_actor_id = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'tenant_id')
        self.tenant_id = attributes[:'tenant_id']
      else
        self.tenant_id = nil
      end

      if attributes.key?(:'variables')
        if (value = attributes[:'variables']).is_a?(Array)
          self.variables = value
        end
      else
        self.variables = nil
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      else
        self.version = nil
      end

      if attributes.key?(:'whatsapp_approval')
        self.whatsapp_approval = attributes[:'whatsapp_approval']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @body.nil?
        invalid_properties.push('invalid value for "body", body cannot be nil.')
      end

      if @channel.nil?
        invalid_properties.push('invalid value for "channel", channel cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @created_by_actor_id.nil?
        invalid_properties.push('invalid value for "created_by_actor_id", created_by_actor_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @tenant_id.nil?
        invalid_properties.push('invalid value for "tenant_id", tenant_id cannot be nil.')
      end

      if @variables.nil?
        invalid_properties.push('invalid value for "variables", variables cannot be nil.')
      end

      if @version.nil?
        invalid_properties.push('invalid value for "version", version cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @body.nil?
      return false if @channel.nil?
      return false if @created_at.nil?
      return false if @created_by_actor_id.nil?
      return false if @id.nil?
      return false if @name.nil?
      return false if @status.nil?
      return false if @tenant_id.nil?
      return false if @variables.nil?
      return false if @version.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] body Value to be assigned
    def body=(body)
      if body.nil?
        fail ArgumentError, 'body cannot be nil'
      end

      @body = body
    end

    # Custom attribute writer method with validation
    # @param [Object] channel Value to be assigned
    def channel=(channel)
      if channel.nil?
        fail ArgumentError, 'channel cannot be nil'
      end

      @channel = channel
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] created_by_actor_id Value to be assigned
    def created_by_actor_id=(created_by_actor_id)
      if created_by_actor_id.nil?
        fail ArgumentError, 'created_by_actor_id cannot be nil'
      end

      @created_by_actor_id = created_by_actor_id
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] tenant_id Value to be assigned
    def tenant_id=(tenant_id)
      if tenant_id.nil?
        fail ArgumentError, 'tenant_id cannot be nil'
      end

      @tenant_id = tenant_id
    end

    # Custom attribute writer method with validation
    # @param [Object] variables Value to be assigned
    def variables=(variables)
      if variables.nil?
        fail ArgumentError, 'variables cannot be nil'
      end

      @variables = variables
    end

    # Custom attribute writer method with validation
    # @param [Object] version Value to be assigned
    def version=(version)
      if version.nil?
        fail ArgumentError, 'version cannot be nil'
      end

      @version = version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          body == o.body &&
          channel == o.channel &&
          created_at == o.created_at &&
          created_by_actor_id == o.created_by_actor_id &&
          id == o.id &&
          name == o.name &&
          status == o.status &&
          subject == o.subject &&
          tenant_id == o.tenant_id &&
          variables == o.variables &&
          version == o.version &&
          whatsapp_approval == o.whatsapp_approval
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [body, channel, created_at, created_by_actor_id, id, name, status, subject, tenant_id, variables, version, whatsapp_approval].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
