=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class PersonInsight < ApiModelBase
    attr_accessor :aka

    attr_accessor :attributes

    attr_accessor :company

    attr_accessor :created_at

    attr_accessor :emails

    attr_accessor :evidence

    attr_accessor :first_name

    attr_accessor :identifiers

    attr_accessor :insights

    attr_accessor :job_position

    attr_accessor :last_name

    attr_accessor :offices

    attr_accessor :organization

    attr_accessor :personal_address

    attr_accessor :phones

    attr_accessor :roles

    attr_accessor :social_profiles

    attr_accessor :sources

    attr_accessor :summary

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aka' => :'aka',
        :'attributes' => :'attributes',
        :'company' => :'company',
        :'created_at' => :'createdAt',
        :'emails' => :'emails',
        :'evidence' => :'evidence',
        :'first_name' => :'firstName',
        :'identifiers' => :'identifiers',
        :'insights' => :'insights',
        :'job_position' => :'jobPosition',
        :'last_name' => :'lastName',
        :'offices' => :'offices',
        :'organization' => :'organization',
        :'personal_address' => :'personalAddress',
        :'phones' => :'phones',
        :'roles' => :'roles',
        :'social_profiles' => :'socialProfiles',
        :'sources' => :'sources',
        :'summary' => :'summary',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aka' => :'Array<String>',
        :'attributes' => :'Array<InsightAttribute>',
        :'company' => :'String',
        :'created_at' => :'String',
        :'emails' => :'Array<String>',
        :'evidence' => :'Array<InsightEvidence>',
        :'first_name' => :'String',
        :'identifiers' => :'Array<InsightIdentifier>',
        :'insights' => :'Array<String>',
        :'job_position' => :'String',
        :'last_name' => :'String',
        :'offices' => :'Array<InsightOffice>',
        :'organization' => :'InsightOrganization',
        :'personal_address' => :'InsightAddress',
        :'phones' => :'Array<InsightPhone>',
        :'roles' => :'Array<InsightRole>',
        :'social_profiles' => :'Array<InsightSocialProfile>',
        :'sources' => :'Array<InsightSource>',
        :'summary' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::PersonInsight` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::PersonInsight`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aka')
        if (value = attributes[:'aka']).is_a?(Array)
          self.aka = value
        end
      end

      if attributes.key?(:'attributes')
        if (value = attributes[:'attributes']).is_a?(Array)
          self.attributes = value
        end
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'emails')
        if (value = attributes[:'emails']).is_a?(Array)
          self.emails = value
        end
      end

      if attributes.key?(:'evidence')
        if (value = attributes[:'evidence']).is_a?(Array)
          self.evidence = value
        end
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'identifiers')
        if (value = attributes[:'identifiers']).is_a?(Array)
          self.identifiers = value
        end
      end

      if attributes.key?(:'insights')
        if (value = attributes[:'insights']).is_a?(Array)
          self.insights = value
        end
      else
        self.insights = nil
      end

      if attributes.key?(:'job_position')
        self.job_position = attributes[:'job_position']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'offices')
        if (value = attributes[:'offices']).is_a?(Array)
          self.offices = value
        end
      end

      if attributes.key?(:'organization')
        self.organization = attributes[:'organization']
      end

      if attributes.key?(:'personal_address')
        self.personal_address = attributes[:'personal_address']
      end

      if attributes.key?(:'phones')
        if (value = attributes[:'phones']).is_a?(Array)
          self.phones = value
        end
      end

      if attributes.key?(:'roles')
        if (value = attributes[:'roles']).is_a?(Array)
          self.roles = value
        end
      end

      if attributes.key?(:'social_profiles')
        if (value = attributes[:'social_profiles']).is_a?(Array)
          self.social_profiles = value
        end
      end

      if attributes.key?(:'sources')
        if (value = attributes[:'sources']).is_a?(Array)
          self.sources = value
        end
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      else
        self.summary = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @insights.nil?
        invalid_properties.push('invalid value for "insights", insights cannot be nil.')
      end

      if @summary.nil?
        invalid_properties.push('invalid value for "summary", summary cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @insights.nil?
      return false if @summary.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] insights Value to be assigned
    def insights=(insights)
      if insights.nil?
        fail ArgumentError, 'insights cannot be nil'
      end

      @insights = insights
    end

    # Custom attribute writer method with validation
    # @param [Object] summary Value to be assigned
    def summary=(summary)
      if summary.nil?
        fail ArgumentError, 'summary cannot be nil'
      end

      @summary = summary
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aka == o.aka &&
          attributes == o.attributes &&
          company == o.company &&
          created_at == o.created_at &&
          emails == o.emails &&
          evidence == o.evidence &&
          first_name == o.first_name &&
          identifiers == o.identifiers &&
          insights == o.insights &&
          job_position == o.job_position &&
          last_name == o.last_name &&
          offices == o.offices &&
          organization == o.organization &&
          personal_address == o.personal_address &&
          phones == o.phones &&
          roles == o.roles &&
          social_profiles == o.social_profiles &&
          sources == o.sources &&
          summary == o.summary &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aka, attributes, company, created_at, emails, evidence, first_name, identifiers, insights, job_position, last_name, offices, organization, personal_address, phones, roles, social_profiles, sources, summary, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
