=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class ProductSequenceRecipientsAddInput < ApiModelBase
    attr_accessor :idempotency_key

    attr_accessor :recipients

    attr_accessor :sequence_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'idempotency_key' => :'idempotencyKey',
        :'recipients' => :'recipients',
        :'sequence_id' => :'sequenceId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'idempotency_key' => :'String',
        :'recipients' => :'Array<ProductSequenceRecipientsAddInputRecipientsInner>',
        :'sequence_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::ProductSequenceRecipientsAddInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::ProductSequenceRecipientsAddInput`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'idempotency_key')
        self.idempotency_key = attributes[:'idempotency_key']
      else
        self.idempotency_key = nil
      end

      if attributes.key?(:'recipients')
        if (value = attributes[:'recipients']).is_a?(Array)
          self.recipients = value
        end
      else
        self.recipients = nil
      end

      if attributes.key?(:'sequence_id')
        self.sequence_id = attributes[:'sequence_id']
      else
        self.sequence_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @idempotency_key.nil?
        invalid_properties.push('invalid value for "idempotency_key", idempotency_key cannot be nil.')
      end

      if @idempotency_key.to_s.length > 200
        invalid_properties.push('invalid value for "idempotency_key", the character length must be smaller than or equal to 200.')
      end

      if @idempotency_key.to_s.length < 16
        invalid_properties.push('invalid value for "idempotency_key", the character length must be greater than or equal to 16.')
      end

      if @recipients.nil?
        invalid_properties.push('invalid value for "recipients", recipients cannot be nil.')
      end

      if @recipients.length > 100
        invalid_properties.push('invalid value for "recipients", number of items must be less than or equal to 100.')
      end

      if @recipients.length < 1
        invalid_properties.push('invalid value for "recipients", number of items must be greater than or equal to 1.')
      end

      if @sequence_id.nil?
        invalid_properties.push('invalid value for "sequence_id", sequence_id cannot be nil.')
      end

      pattern = Regexp.new(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
      if @sequence_id !~ pattern
        invalid_properties.push("invalid value for \"sequence_id\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @idempotency_key.nil?
      return false if @idempotency_key.to_s.length > 200
      return false if @idempotency_key.to_s.length < 16
      return false if @recipients.nil?
      return false if @recipients.length > 100
      return false if @recipients.length < 1
      return false if @sequence_id.nil?
      return false if @sequence_id !~ Regexp.new(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] idempotency_key Value to be assigned
    def idempotency_key=(idempotency_key)
      if idempotency_key.nil?
        fail ArgumentError, 'idempotency_key cannot be nil'
      end

      if idempotency_key.to_s.length > 200
        fail ArgumentError, 'invalid value for "idempotency_key", the character length must be smaller than or equal to 200.'
      end

      if idempotency_key.to_s.length < 16
        fail ArgumentError, 'invalid value for "idempotency_key", the character length must be greater than or equal to 16.'
      end

      @idempotency_key = idempotency_key
    end

    # Custom attribute writer method with validation
    # @param [Object] recipients Value to be assigned
    def recipients=(recipients)
      if recipients.nil?
        fail ArgumentError, 'recipients cannot be nil'
      end

      if recipients.length > 100
        fail ArgumentError, 'invalid value for "recipients", number of items must be less than or equal to 100.'
      end

      if recipients.length < 1
        fail ArgumentError, 'invalid value for "recipients", number of items must be greater than or equal to 1.'
      end

      @recipients = recipients
    end

    # Custom attribute writer method with validation
    # @param [Object] sequence_id Value to be assigned
    def sequence_id=(sequence_id)
      if sequence_id.nil?
        fail ArgumentError, 'sequence_id cannot be nil'
      end

      pattern = Regexp.new(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
      if sequence_id !~ pattern
        fail ArgumentError, "invalid value for \"sequence_id\", must conform to the pattern #{pattern}."
      end

      @sequence_id = sequence_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          idempotency_key == o.idempotency_key &&
          recipients == o.recipients &&
          sequence_id == o.sequence_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [idempotency_key, recipients, sequence_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
