=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class StartIntegrationOAuthRequest < ApiModelBase
    attr_accessor :authorization_server

    attr_accessor :resource_url

    attr_accessor :return_path

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'authorization_server' => :'authorizationServer',
        :'resource_url' => :'resourceUrl',
        :'return_path' => :'returnPath'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'authorization_server' => :'String',
        :'resource_url' => :'String',
        :'return_path' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::StartIntegrationOAuthRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::StartIntegrationOAuthRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'authorization_server')
        self.authorization_server = attributes[:'authorization_server']
      end

      if attributes.key?(:'resource_url')
        self.resource_url = attributes[:'resource_url']
      end

      if attributes.key?(:'return_path')
        self.return_path = attributes[:'return_path']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@authorization_server.nil? && @authorization_server.to_s.length > 2048
        invalid_properties.push('invalid value for "authorization_server", the character length must be smaller than or equal to 2048.')
      end

      if !@authorization_server.nil? && @authorization_server.to_s.length < 8
        invalid_properties.push('invalid value for "authorization_server", the character length must be greater than or equal to 8.')
      end

      if !@resource_url.nil? && @resource_url.to_s.length > 2048
        invalid_properties.push('invalid value for "resource_url", the character length must be smaller than or equal to 2048.')
      end

      if !@resource_url.nil? && @resource_url.to_s.length < 8
        invalid_properties.push('invalid value for "resource_url", the character length must be greater than or equal to 8.')
      end

      if !@return_path.nil? && @return_path.to_s.length > 1024
        invalid_properties.push('invalid value for "return_path", the character length must be smaller than or equal to 1024.')
      end

      if !@return_path.nil? && @return_path.to_s.length < 1
        invalid_properties.push('invalid value for "return_path", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@authorization_server.nil? && @authorization_server.to_s.length > 2048
      return false if !@authorization_server.nil? && @authorization_server.to_s.length < 8
      return false if !@resource_url.nil? && @resource_url.to_s.length > 2048
      return false if !@resource_url.nil? && @resource_url.to_s.length < 8
      return false if !@return_path.nil? && @return_path.to_s.length > 1024
      return false if !@return_path.nil? && @return_path.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] authorization_server Value to be assigned
    def authorization_server=(authorization_server)
      if authorization_server.nil?
        fail ArgumentError, 'authorization_server cannot be nil'
      end

      if authorization_server.to_s.length > 2048
        fail ArgumentError, 'invalid value for "authorization_server", the character length must be smaller than or equal to 2048.'
      end

      if authorization_server.to_s.length < 8
        fail ArgumentError, 'invalid value for "authorization_server", the character length must be greater than or equal to 8.'
      end

      @authorization_server = authorization_server
    end

    # Custom attribute writer method with validation
    # @param [Object] resource_url Value to be assigned
    def resource_url=(resource_url)
      if resource_url.nil?
        fail ArgumentError, 'resource_url cannot be nil'
      end

      if resource_url.to_s.length > 2048
        fail ArgumentError, 'invalid value for "resource_url", the character length must be smaller than or equal to 2048.'
      end

      if resource_url.to_s.length < 8
        fail ArgumentError, 'invalid value for "resource_url", the character length must be greater than or equal to 8.'
      end

      @resource_url = resource_url
    end

    # Custom attribute writer method with validation
    # @param [Object] return_path Value to be assigned
    def return_path=(return_path)
      if return_path.nil?
        fail ArgumentError, 'return_path cannot be nil'
      end

      if return_path.to_s.length > 1024
        fail ArgumentError, 'invalid value for "return_path", the character length must be smaller than or equal to 1024.'
      end

      if return_path.to_s.length < 1
        fail ArgumentError, 'invalid value for "return_path", the character length must be greater than or equal to 1.'
      end

      @return_path = return_path
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          authorization_server == o.authorization_server &&
          resource_url == o.resource_url &&
          return_path == o.return_path
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [authorization_server, resource_url, return_path].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
