=begin
#Reacon API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module Reacon
  class UpdateLeadRequestCompany < ApiModelBase
    attr_accessor :addresses

    attr_accessor :founded_on

    attr_accessor :industry

    attr_accessor :linkedin

    attr_accessor :location

    attr_accessor :name

    attr_accessor :number_of_employees

    attr_accessor :stock

    attr_accessor :twitter

    attr_accessor :type

    attr_accessor :website

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'addresses' => :'addresses',
        :'founded_on' => :'founded_on',
        :'industry' => :'industry',
        :'linkedin' => :'linkedin',
        :'location' => :'location',
        :'name' => :'name',
        :'number_of_employees' => :'number_of_employees',
        :'stock' => :'stock',
        :'twitter' => :'twitter',
        :'type' => :'type',
        :'website' => :'website'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'addresses' => :'Array<CompanyListResultsInnerAddressesInner>',
        :'founded_on' => :'String',
        :'industry' => :'String',
        :'linkedin' => :'String',
        :'location' => :'String',
        :'name' => :'String',
        :'number_of_employees' => :'Integer',
        :'stock' => :'String',
        :'twitter' => :'String',
        :'type' => :'String',
        :'website' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'addresses',
        :'founded_on',
        :'industry',
        :'linkedin',
        :'location',
        :'name',
        :'number_of_employees',
        :'stock',
        :'twitter',
        :'type',
        :'website'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Reacon::UpdateLeadRequestCompany` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Reacon::UpdateLeadRequestCompany`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'addresses')
        value = attributes[:'addresses']
        if value.nil? || value.is_a?(Array)
          self.addresses = value
        end
      end

      if attributes.key?(:'founded_on')
        self.founded_on = attributes[:'founded_on']
      end

      if attributes.key?(:'industry')
        self.industry = attributes[:'industry']
      end

      if attributes.key?(:'linkedin')
        self.linkedin = attributes[:'linkedin']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'number_of_employees')
        self.number_of_employees = attributes[:'number_of_employees']
      end

      if attributes.key?(:'stock')
        self.stock = attributes[:'stock']
      end

      if attributes.key?(:'twitter')
        self.twitter = attributes[:'twitter']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'website')
        self.website = attributes[:'website']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          addresses == o.addresses &&
          founded_on == o.founded_on &&
          industry == o.industry &&
          linkedin == o.linkedin &&
          location == o.location &&
          name == o.name &&
          number_of_employees == o.number_of_employees &&
          stock == o.stock &&
          twitter == o.twitter &&
          type == o.type &&
          website == o.website
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [addresses, founded_on, industry, linkedin, location, name, number_of_employees, stock, twitter, type, website].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
